/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExtAlbumOrderOptions,
  ExtAlbumReadDto,
  ExtAlbumsListResult,
  ExtSortOrder,
} from '../models/index';
import {
    ExtAlbumOrderOptionsFromJSON,
    ExtAlbumOrderOptionsToJSON,
    ExtAlbumReadDtoFromJSON,
    ExtAlbumReadDtoToJSON,
    ExtAlbumsListResultFromJSON,
    ExtAlbumsListResultToJSON,
    ExtSortOrderFromJSON,
    ExtSortOrderToJSON,
} from '../models/index';

export interface GetAlbumRequest {
    id: string;
}

export interface GetAlbumFilteredRequest {
    title?: string;
    releaseDateBegin?: Date;
    releaseDateEnd?: Date;
    convention?: string;
    catalog?: string;
    artist?: string;
    artistId?: string;
    start?: number;
    limit?: number;
}

export interface GetAlbumsRequest {
    start?: number;
    limit?: number;
    sort?: ExtAlbumOrderOptions;
    sortOrder?: ExtSortOrder;
}

export interface GetAlbumsByIdsRequest {
    requestBody?: Array<string>;
}

/**
 * 
 */
export class AlbumApi extends runtime.BaseAPI {

    /**
     */
    async countAlbumsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExtAlbumReadDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/music/album/count`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExtAlbumReadDtoFromJSON));
    }

    /**
     */
    async countAlbums(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExtAlbumReadDto>> {
        const response = await this.countAlbumsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getAlbumRaw(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtAlbumReadDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/music/album/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtAlbumReadDtoFromJSON(jsonValue));
    }

    /**
     */
    async getAlbum(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtAlbumReadDto> {
        const response = await this.getAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAlbumFilteredRaw(requestParameters: GetAlbumFilteredRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExtAlbumReadDto>>> {
        const queryParameters: any = {};

        if (requestParameters['title'] != null) {
            queryParameters['Title'] = requestParameters['title'];
        }

        if (requestParameters['releaseDateBegin'] != null) {
            queryParameters['ReleaseDateBegin'] = (requestParameters['releaseDateBegin'] as any).toISOString();
        }

        if (requestParameters['releaseDateEnd'] != null) {
            queryParameters['ReleaseDateEnd'] = (requestParameters['releaseDateEnd'] as any).toISOString();
        }

        if (requestParameters['convention'] != null) {
            queryParameters['Convention'] = requestParameters['convention'];
        }

        if (requestParameters['catalog'] != null) {
            queryParameters['Catalog'] = requestParameters['catalog'];
        }

        if (requestParameters['artist'] != null) {
            queryParameters['Artist'] = requestParameters['artist'];
        }

        if (requestParameters['artistId'] != null) {
            queryParameters['ArtistId'] = requestParameters['artistId'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/music/album/filter`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExtAlbumReadDtoFromJSON));
    }

    /**
     */
    async getAlbumFiltered(requestParameters: GetAlbumFilteredRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExtAlbumReadDto>> {
        const response = await this.getAlbumFilteredRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAlbumsRaw(requestParameters: GetAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtAlbumsListResult>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/music/album`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtAlbumsListResultFromJSON(jsonValue));
    }

    /**
     */
    async getAlbums(requestParameters: GetAlbumsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtAlbumsListResult> {
        const response = await this.getAlbumsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAlbumsByIdsRaw(requestParameters: GetAlbumsByIdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExtAlbumReadDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/music/album`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExtAlbumReadDtoFromJSON));
    }

    /**
     */
    async getAlbumsByIds(requestParameters: GetAlbumsByIdsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExtAlbumReadDto>> {
        const response = await this.getAlbumsByIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
