/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExtAlbumOrderOptions,
  ExtAlbumsListResult,
  ExtCircleReadDto,
  ExtSortOrder,
} from '../models/index';
import {
    ExtAlbumOrderOptionsFromJSON,
    ExtAlbumOrderOptionsToJSON,
    ExtAlbumsListResultFromJSON,
    ExtAlbumsListResultToJSON,
    ExtCircleReadDtoFromJSON,
    ExtCircleReadDtoToJSON,
    ExtSortOrderFromJSON,
    ExtSortOrderToJSON,
} from '../models/index';

export interface GetCircleAlbumsByIdRequest {
    id: string;
    start?: number;
    limit?: number;
    sort?: ExtAlbumOrderOptions;
    sortOrder?: ExtSortOrder;
}

export interface GetCircleAlbumsByNameRequest {
    name: string;
    start?: number;
    limit?: number;
    sort?: ExtAlbumOrderOptions;
    sortOrder?: ExtSortOrder;
}

export interface GetCircleByIdRequest {
    id: string;
}

export interface GetCircleByNameRequest {
    name: string;
}

export interface GetCirclesRequest {
    start?: number;
    limit?: number;
}

/**
 * 
 */
export class CircleApi extends runtime.BaseAPI {

    /**
     */
    async getCircleAlbumsByIdRaw(requestParameters: GetCircleAlbumsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtAlbumsListResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCircleAlbumsById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entity/circle/{id}/albums`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtAlbumsListResultFromJSON(jsonValue));
    }

    /**
     */
    async getCircleAlbumsById(requestParameters: GetCircleAlbumsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtAlbumsListResult> {
        const response = await this.getCircleAlbumsByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCircleAlbumsByNameRaw(requestParameters: GetCircleAlbumsByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtAlbumsListResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getCircleAlbumsByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entity/circle/{name}/albums`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtAlbumsListResultFromJSON(jsonValue));
    }

    /**
     */
    async getCircleAlbumsByName(requestParameters: GetCircleAlbumsByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtAlbumsListResult> {
        const response = await this.getCircleAlbumsByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCircleByIdRaw(requestParameters: GetCircleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtCircleReadDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCircleById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entity/circle/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtCircleReadDtoFromJSON(jsonValue));
    }

    /**
     */
    async getCircleById(requestParameters: GetCircleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtCircleReadDto> {
        const response = await this.getCircleByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCircleByNameRaw(requestParameters: GetCircleByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtCircleReadDto>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getCircleByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entity/circle/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtCircleReadDtoFromJSON(jsonValue));
    }

    /**
     */
    async getCircleByName(requestParameters: GetCircleByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtCircleReadDto> {
        const response = await this.getCircleByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCirclesRaw(requestParameters: GetCirclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExtCircleReadDto>>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/entity/circle`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExtCircleReadDtoFromJSON));
    }

    /**
     */
    async getCircles(requestParameters: GetCirclesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExtCircleReadDto>> {
        const response = await this.getCirclesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
