/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlbumWriteDto,
  Asset,
  CircleWriteDto,
  HlsPlaylistWriteDto,
  HlsSegmentWriteDto,
  Lyrics,
  Operation,
  TrackUpdateDto,
  TrackWriteDto,
} from '../models/index';
import {
    AlbumWriteDtoFromJSON,
    AlbumWriteDtoToJSON,
    AssetFromJSON,
    AssetToJSON,
    CircleWriteDtoFromJSON,
    CircleWriteDtoToJSON,
    HlsPlaylistWriteDtoFromJSON,
    HlsPlaylistWriteDtoToJSON,
    HlsSegmentWriteDtoFromJSON,
    HlsSegmentWriteDtoToJSON,
    LyricsFromJSON,
    LyricsToJSON,
    OperationFromJSON,
    OperationToJSON,
    TrackUpdateDtoFromJSON,
    TrackUpdateDtoToJSON,
    TrackWriteDtoFromJSON,
    TrackWriteDtoToJSON,
} from '../models/index';

export interface INTERNALAddAlbumRequest {
    albumId: string;
    parentId?: string;
    albumWriteDto?: AlbumWriteDto;
}

export interface INTERNALAddAssetUncheckedRequest {
    asset?: Asset;
}

export interface INTERNALAddCircleRequest {
    id: string;
    circleWriteDto?: CircleWriteDto;
}

export interface INTERNALAddHlsFilePlaylistRequest {
    trackId: string;
    hlsPlaylistWriteDto?: HlsPlaylistWriteDto;
}

export interface INTERNALAddHlsFileSegmentRequest {
    trackId: string;
    quality?: number;
    hlsSegmentWriteDto?: HlsSegmentWriteDto;
}

export interface INTERNALAddLyricsRequest {
    trackId: string;
    lyricsId: string;
    lyrics?: Lyrics;
}

export interface INTERNALAddTrackRequest {
    albumId: string;
    trackId: string;
    trackWriteDto?: TrackWriteDto;
}

export interface INTERNALPATCHUpdateTrackRequest {
    trackId: string;
    operation?: Array<Operation>;
}

export interface INTERNALUpdateAlbumRequest {
    albumId: string;
    operation?: Array<Operation>;
}

export interface INTERNALUpdateCircleRequest {
    id: string;
    operation?: Array<Operation>;
}

export interface INTERNALUpdateTrackRequest {
    trackId: string;
    trackUpdateDto?: TrackUpdateDto;
}

/**
 * 
 */
export class InternalApi extends runtime.BaseAPI {

    /**
     */
    async iNTERNALAddAlbumRaw(requestParameters: INTERNALAddAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling iNTERNALAddAlbum().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['parentId'] != null) {
            queryParameters['parentId'] = requestParameters['parentId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/album/add/{albumId}`.replace(`{${"albumId"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumWriteDtoToJSON(requestParameters['albumWriteDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddAlbum(requestParameters: INTERNALAddAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddAlbumRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALAddAssetUncheckedRaw(requestParameters: INTERNALAddAssetUncheckedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/asset/add`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AssetToJSON(requestParameters['asset']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddAssetUnchecked(requestParameters: INTERNALAddAssetUncheckedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddAssetUncheckedRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALAddCircleRaw(requestParameters: INTERNALAddCircleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling iNTERNALAddCircle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/circle/add/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CircleWriteDtoToJSON(requestParameters['circleWriteDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddCircle(requestParameters: INTERNALAddCircleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddCircleRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALAddHlsFilePlaylistRaw(requestParameters: INTERNALAddHlsFilePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling iNTERNALAddHlsFilePlaylist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/asset/track/{trackId}/playlist`.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HlsPlaylistWriteDtoToJSON(requestParameters['hlsPlaylistWriteDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddHlsFilePlaylist(requestParameters: INTERNALAddHlsFilePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddHlsFilePlaylistRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALAddHlsFileSegmentRaw(requestParameters: INTERNALAddHlsFileSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling iNTERNALAddHlsFileSegment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['quality'] != null) {
            queryParameters['quality'] = requestParameters['quality'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/asset/track/{trackId}/segment`.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HlsSegmentWriteDtoToJSON(requestParameters['hlsSegmentWriteDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddHlsFileSegment(requestParameters: INTERNALAddHlsFileSegmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddHlsFileSegmentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALAddLyricsRaw(requestParameters: INTERNALAddLyricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling iNTERNALAddLyrics().'
            );
        }

        if (requestParameters['lyricsId'] == null) {
            throw new runtime.RequiredError(
                'lyricsId',
                'Required parameter "lyricsId" was null or undefined when calling iNTERNALAddLyrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/track/{trackId}/lyrics/add/{lyricsId}`.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId']))).replace(`{${"lyricsId"}}`, encodeURIComponent(String(requestParameters['lyricsId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LyricsToJSON(requestParameters['lyrics']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddLyrics(requestParameters: INTERNALAddLyricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddLyricsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALAddTrackRaw(requestParameters: INTERNALAddTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling iNTERNALAddTrack().'
            );
        }

        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling iNTERNALAddTrack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/album/{albumId}/track/add/{trackId}`.replace(`{${"albumId"}}`, encodeURIComponent(String(requestParameters['albumId']))).replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TrackWriteDtoToJSON(requestParameters['trackWriteDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALAddTrack(requestParameters: INTERNALAddTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALAddTrackRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALPATCHUpdateTrackRaw(requestParameters: INTERNALPATCHUpdateTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling iNTERNALPATCHUpdateTrack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/track/jsonpatch/{trackId}`.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['operation']!.map(OperationToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALPATCHUpdateTrack(requestParameters: INTERNALPATCHUpdateTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALPATCHUpdateTrackRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALUpdateAlbumRaw(requestParameters: INTERNALUpdateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling iNTERNALUpdateAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/album/{albumId}`.replace(`{${"albumId"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['operation']!.map(OperationToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALUpdateAlbum(requestParameters: INTERNALUpdateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALUpdateAlbumRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALUpdateCircleRaw(requestParameters: INTERNALUpdateCircleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling iNTERNALUpdateCircle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/circle/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['operation']!.map(OperationToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALUpdateCircle(requestParameters: INTERNALUpdateCircleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALUpdateCircleRaw(requestParameters, initOverrides);
    }

    /**
     */
    async iNTERNALUpdateTrackRaw(requestParameters: INTERNALUpdateTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling iNTERNALUpdateTrack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/internal/track/{trackId}`.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TrackUpdateDtoToJSON(requestParameters['trackUpdateDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async iNTERNALUpdateTrack(requestParameters: INTERNALUpdateTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.iNTERNALUpdateTrackRaw(requestParameters, initOverrides);
    }

}
