/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExtOriginalAlbumReadDto,
  ExtOriginalAlbumReadDtoActionResult,
  ExtOriginalAlbumWriteDto,
  ExtOriginalTrackReadDto,
  ExtOriginalTrackReadDtoActionResult,
  ExtOriginalTrackWriteDto,
} from '../models/index';
import {
    ExtOriginalAlbumReadDtoFromJSON,
    ExtOriginalAlbumReadDtoToJSON,
    ExtOriginalAlbumReadDtoActionResultFromJSON,
    ExtOriginalAlbumReadDtoActionResultToJSON,
    ExtOriginalAlbumWriteDtoFromJSON,
    ExtOriginalAlbumWriteDtoToJSON,
    ExtOriginalTrackReadDtoFromJSON,
    ExtOriginalTrackReadDtoToJSON,
    ExtOriginalTrackReadDtoActionResultFromJSON,
    ExtOriginalTrackReadDtoActionResultToJSON,
    ExtOriginalTrackWriteDtoFromJSON,
    ExtOriginalTrackWriteDtoToJSON,
} from '../models/index';

export interface AddOriginalAlbumRequest {
    extOriginalAlbumWriteDto?: ExtOriginalAlbumWriteDto;
}

export interface AddOriginalTrackRequest {
    albumId: string;
    extOriginalTrackWriteDto?: ExtOriginalTrackWriteDto;
}

export interface GetOriginalAlbumRequest {
    id: string;
}

export interface GetOriginalAlbumsRequest {
    start?: number;
    limit?: number;
}

export interface GetOriginalTrackRequest {
    id: string;
}

export interface GetOriginalTracksRequest {
    start?: number;
    limit?: number;
}

/**
 * 
 */
export class OriginalAlbumApi extends runtime.BaseAPI {

    /**
     */
    async addOriginalAlbumRaw(requestParameters: AddOriginalAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtOriginalAlbumReadDtoActionResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/source/album`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExtOriginalAlbumWriteDtoToJSON(requestParameters['extOriginalAlbumWriteDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtOriginalAlbumReadDtoActionResultFromJSON(jsonValue));
    }

    /**
     */
    async addOriginalAlbum(requestParameters: AddOriginalAlbumRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtOriginalAlbumReadDtoActionResult> {
        const response = await this.addOriginalAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async addOriginalTrackRaw(requestParameters: AddOriginalTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtOriginalTrackReadDtoActionResult>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling addOriginalTrack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/source/album/{albumId}/track`.replace(`{${"albumId"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExtOriginalTrackWriteDtoToJSON(requestParameters['extOriginalTrackWriteDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtOriginalTrackReadDtoActionResultFromJSON(jsonValue));
    }

    /**
     */
    async addOriginalTrack(requestParameters: AddOriginalTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtOriginalTrackReadDtoActionResult> {
        const response = await this.addOriginalTrackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOriginalAlbumRaw(requestParameters: GetOriginalAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtOriginalAlbumReadDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOriginalAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/source/album/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtOriginalAlbumReadDtoFromJSON(jsonValue));
    }

    /**
     */
    async getOriginalAlbum(requestParameters: GetOriginalAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtOriginalAlbumReadDto> {
        const response = await this.getOriginalAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOriginalAlbumsRaw(requestParameters: GetOriginalAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExtOriginalAlbumReadDto>>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/source/album`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExtOriginalAlbumReadDtoFromJSON));
    }

    /**
     */
    async getOriginalAlbums(requestParameters: GetOriginalAlbumsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExtOriginalAlbumReadDto>> {
        const response = await this.getOriginalAlbumsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOriginalTrackRaw(requestParameters: GetOriginalTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtOriginalTrackReadDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOriginalTrack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/source/track/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtOriginalTrackReadDtoFromJSON(jsonValue));
    }

    /**
     */
    async getOriginalTrack(requestParameters: GetOriginalTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtOriginalTrackReadDto> {
        const response = await this.getOriginalTrackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOriginalTracksRaw(requestParameters: GetOriginalTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExtOriginalTrackReadDto>>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/source/track`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExtOriginalTrackReadDtoFromJSON));
    }

    /**
     */
    async getOriginalTracks(requestParameters: GetOriginalTracksRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExtOriginalTrackReadDto>> {
        const response = await this.getOriginalTracksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
