/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
} from './Asset';
import type { LocalizedField } from './LocalizedField';
import {
    LocalizedFieldFromJSON,
    LocalizedFieldFromJSONTyped,
    LocalizedFieldToJSON,
} from './LocalizedField';
import type { Track } from './Track';
import {
    TrackFromJSON,
    TrackFromJSONTyped,
    TrackToJSON,
} from './Track';

/**
 * 
 * @export
 * @interface Album
 */
export interface Album {
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    id?: string;
    /**
     * 
     * @type {LocalizedField}
     * @memberof Album
     */
    albumName: LocalizedField;
    /**
     * 
     * @type {Date}
     * @memberof Album
     */
    releaseDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    releaseConvention?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    catalogNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    numberOfDiscs: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Album
     */
    website?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Album
     */
    albumArtist: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Album
     */
    dataSource?: Array<string> | null;
    /**
     * 
     * @type {Array<Track>}
     * @memberof Album
     */
    tracks?: Array<Track> | null;
    /**
     * 
     * @type {Array<Album>}
     * @memberof Album
     */
    linkedAlbums?: Array<Album> | null;
    /**
     * 
     * @type {Asset}
     * @memberof Album
     */
    albumImage?: Asset;
    /**
     * 
     * @type {Array<Asset>}
     * @memberof Album
     */
    otherImages?: Array<Asset> | null;
}

/**
 * Check if a given object implements the Album interface.
 */
export function instanceOfAlbum(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "albumName" in value;
    isInstance = isInstance && "numberOfDiscs" in value;
    isInstance = isInstance && "albumArtist" in value;

    return isInstance;
}

export function AlbumFromJSON(json: any): Album {
    return AlbumFromJSONTyped(json, false);
}

export function AlbumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Album {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'albumName': LocalizedFieldFromJSON(json['albumName']),
        'releaseDate': !exists(json, 'releaseDate') ? undefined : (json['releaseDate'] === null ? null : new Date(json['releaseDate'])),
        'releaseConvention': !exists(json, 'releaseConvention') ? undefined : json['releaseConvention'],
        'catalogNumber': !exists(json, 'catalogNumber') ? undefined : json['catalogNumber'],
        'numberOfDiscs': json['numberOfDiscs'],
        'website': !exists(json, 'website') ? undefined : json['website'],
        'albumArtist': json['albumArtist'],
        'dataSource': !exists(json, 'dataSource') ? undefined : json['dataSource'],
        'tracks': !exists(json, 'tracks') ? undefined : (json['tracks'] === null ? null : (json['tracks'] as Array<any>).map(TrackFromJSON)),
        'linkedAlbums': !exists(json, 'linkedAlbums') ? undefined : (json['linkedAlbums'] === null ? null : (json['linkedAlbums'] as Array<any>).map(AlbumFromJSON)),
        'albumImage': !exists(json, 'albumImage') ? undefined : AssetFromJSON(json['albumImage']),
        'otherImages': !exists(json, 'otherImages') ? undefined : (json['otherImages'] === null ? null : (json['otherImages'] as Array<any>).map(AssetFromJSON)),
    };
}

export function AlbumToJSON(value?: Album | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'albumName': LocalizedFieldToJSON(value.albumName),
        'releaseDate': value.releaseDate === undefined ? undefined : (value.releaseDate === null ? null : value.releaseDate.toISOString()),
        'releaseConvention': value.releaseConvention,
        'catalogNumber': value.catalogNumber,
        'numberOfDiscs': value.numberOfDiscs,
        'website': value.website,
        'albumArtist': value.albumArtist,
        'dataSource': value.dataSource,
        'tracks': value.tracks === undefined ? undefined : (value.tracks === null ? null : (value.tracks as Array<any>).map(TrackToJSON)),
        'linkedAlbums': value.linkedAlbums === undefined ? undefined : (value.linkedAlbums === null ? null : (value.linkedAlbums as Array<any>).map(AlbumToJSON)),
        'albumImage': AssetToJSON(value.albumImage),
        'otherImages': value.otherImages === undefined ? undefined : (value.otherImages === null ? null : (value.otherImages as Array<any>).map(AssetToJSON)),
    };
}

