/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetId: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetName: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetPath: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    assetMime?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Asset
     */
    large?: boolean;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "assetId" in value;
    isInstance = isInstance && "assetName" in value;
    isInstance = isInstance && "assetPath" in value;

    return isInstance;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assetId': json['assetId'],
        'assetName': json['assetName'],
        'assetPath': json['assetPath'],
        'assetMime': !exists(json, 'assetMime') ? undefined : json['assetMime'],
        'large': !exists(json, 'large') ? undefined : json['large'],
    };
}

export function AssetToJSON(value?: Asset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assetId': value.assetId,
        'assetName': value.assetName,
        'assetPath': value.assetPath,
        'assetMime': value.assetMime,
        'large': value.large,
    };
}

