/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CircleReadDto
 */
export interface CircleReadDto {
    /**
     * 
     * @type {string}
     * @memberof CircleReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CircleReadDto
     */
    name?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CircleReadDto
     */
    alias?: Array<string> | null;
}

/**
 * Check if a given object implements the CircleReadDto interface.
 */
export function instanceOfCircleReadDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CircleReadDtoFromJSON(json: any): CircleReadDto {
    return CircleReadDtoFromJSONTyped(json, false);
}

export function CircleReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircleReadDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
    };
}

export function CircleReadDtoToJSON(value?: CircleReadDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'alias': value.alias,
    };
}

