/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocalizedField } from './LocalizedField';
import {
    LocalizedFieldFromJSON,
    LocalizedFieldFromJSONTyped,
    LocalizedFieldToJSON,
} from './LocalizedField';
import type { OriginalTrack } from './OriginalTrack';
import {
    OriginalTrackFromJSON,
    OriginalTrackFromJSONTyped,
    OriginalTrackToJSON,
} from './OriginalTrack';

/**
 * 
 * @export
 * @interface OriginalAlbum
 */
export interface OriginalAlbum {
    /**
     * 
     * @type {string}
     * @memberof OriginalAlbum
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OriginalAlbum
     */
    type: string;
    /**
     * 
     * @type {LocalizedField}
     * @memberof OriginalAlbum
     */
    fullName: LocalizedField;
    /**
     * 
     * @type {LocalizedField}
     * @memberof OriginalAlbum
     */
    shortName: LocalizedField;
    /**
     * 
     * @type {string}
     * @memberof OriginalAlbum
     */
    externalReference?: string | null;
    /**
     * 
     * @type {Array<OriginalTrack>}
     * @memberof OriginalAlbum
     */
    tracks?: Array<OriginalTrack> | null;
}

/**
 * Check if a given object implements the OriginalAlbum interface.
 */
export function instanceOfOriginalAlbum(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "shortName" in value;

    return isInstance;
}

export function OriginalAlbumFromJSON(json: any): OriginalAlbum {
    return OriginalAlbumFromJSONTyped(json, false);
}

export function OriginalAlbumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginalAlbum {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'fullName': LocalizedFieldFromJSON(json['fullName']),
        'shortName': LocalizedFieldFromJSON(json['shortName']),
        'externalReference': !exists(json, 'externalReference') ? undefined : json['externalReference'],
        'tracks': !exists(json, 'tracks') ? undefined : (json['tracks'] === null ? null : (json['tracks'] as Array<any>).map(OriginalTrackFromJSON)),
    };
}

export function OriginalAlbumToJSON(value?: OriginalAlbum | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'fullName': LocalizedFieldToJSON(value.fullName),
        'shortName': LocalizedFieldToJSON(value.shortName),
        'externalReference': value.externalReference,
        'tracks': value.tracks === undefined ? undefined : (value.tracks === null ? null : (value.tracks as Array<any>).map(OriginalTrackToJSON)),
    };
}

