/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';

/**
 * 
 * @export
 * @interface ExtAlbumWriteDto
 */
export interface ExtAlbumWriteDto {
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtAlbumWriteDto
     */
    albumName: ExtLocalizedField;
    /**
     * 
     * @type {Date}
     * @memberof ExtAlbumWriteDto
     */
    releaseDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExtAlbumWriteDto
     */
    releaseConvention?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtAlbumWriteDto
     */
    catalogNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtAlbumWriteDto
     */
    numberOfDiscs?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtAlbumWriteDto
     */
    discNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtAlbumWriteDto
     */
    discName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtAlbumWriteDto
     */
    website?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtAlbumWriteDto
     */
    albumArtist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtAlbumWriteDto
     */
    genre?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtAlbumWriteDto
     */
    dataSource?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ExtAlbumWriteDto
     */
    albumImage?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtAlbumWriteDto
     */
    otherFiles?: Array<string>;
}

/**
 * Check if a given object implements the ExtAlbumWriteDto interface.
 */
export function instanceOfExtAlbumWriteDto(value: object): boolean {
    if (!('albumName' in value)) return false;
    return true;
}

export function ExtAlbumWriteDtoFromJSON(json: any): ExtAlbumWriteDto {
    return ExtAlbumWriteDtoFromJSONTyped(json, false);
}

export function ExtAlbumWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtAlbumWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'albumName': ExtLocalizedFieldFromJSON(json['albumName']),
        'releaseDate': json['releaseDate'] == null ? undefined : (new Date(json['releaseDate'])),
        'releaseConvention': json['releaseConvention'] == null ? undefined : json['releaseConvention'],
        'catalogNumber': json['catalogNumber'] == null ? undefined : json['catalogNumber'],
        'numberOfDiscs': json['numberOfDiscs'] == null ? undefined : json['numberOfDiscs'],
        'discNumber': json['discNumber'] == null ? undefined : json['discNumber'],
        'discName': json['discName'] == null ? undefined : json['discName'],
        'website': json['website'] == null ? undefined : json['website'],
        'albumArtist': json['albumArtist'] == null ? undefined : json['albumArtist'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'dataSource': json['dataSource'] == null ? undefined : json['dataSource'],
        'albumImage': json['albumImage'] == null ? undefined : json['albumImage'],
        'otherFiles': json['otherFiles'] == null ? undefined : json['otherFiles'],
    };
}

export function ExtAlbumWriteDtoToJSON(value?: ExtAlbumWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'albumName': ExtLocalizedFieldToJSON(value['albumName']),
        'releaseDate': value['releaseDate'] == null ? undefined : ((value['releaseDate'] as any).toISOString()),
        'releaseConvention': value['releaseConvention'],
        'catalogNumber': value['catalogNumber'],
        'numberOfDiscs': value['numberOfDiscs'],
        'discNumber': value['discNumber'],
        'discName': value['discName'],
        'website': value['website'],
        'albumArtist': value['albumArtist'],
        'genre': value['genre'],
        'dataSource': value['dataSource'],
        'albumImage': value['albumImage'],
        'otherFiles': value['otherFiles'],
    };
}

