/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtAsset
 */
export interface ExtAsset {
    /**
     * 
     * @type {string}
     * @memberof ExtAsset
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExtAsset
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExtAsset
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof ExtAsset
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtAsset
     */
    size?: number;
}

/**
 * Check if a given object implements the ExtAsset interface.
 */
export function instanceOfExtAsset(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('path' in value)) return false;
    return true;
}

export function ExtAssetFromJSON(json: any): ExtAsset {
    return ExtAssetFromJSONTyped(json, false);
}

export function ExtAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'path': json['path'],
        'mime': json['mime'] == null ? undefined : json['mime'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function ExtAssetToJSON(value?: ExtAsset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'path': value['path'],
        'mime': value['mime'],
        'size': value['size'],
    };
}

