/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtAlbumReadDto } from './ExtAlbumReadDto';
import {
    ExtAlbumReadDtoFromJSON,
    ExtAlbumReadDtoFromJSONTyped,
    ExtAlbumReadDtoToJSON,
} from './ExtAlbumReadDto';

/**
 * 
 * @export
 * @interface ExtAlbumsListResult
 */
export interface ExtAlbumsListResult {
    /**
     * 
     * @type {Array<ExtAlbumReadDto>}
     * @memberof ExtAlbumsListResult
     */
    albums?: Array<ExtAlbumReadDto>;
    /**
     * 
     * @type {number}
     * @memberof ExtAlbumsListResult
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtAlbumsListResult
     */
    total?: number;
}

/**
 * Check if a given object implements the ExtAlbumsListResult interface.
 */
export function instanceOfExtAlbumsListResult(value: object): boolean {
    return true;
}

export function ExtAlbumsListResultFromJSON(json: any): ExtAlbumsListResult {
    return ExtAlbumsListResultFromJSONTyped(json, false);
}

export function ExtAlbumsListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtAlbumsListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'albums': json['albums'] == null ? undefined : ((json['albums'] as Array<any>).map(ExtAlbumReadDtoFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ExtAlbumsListResultToJSON(value?: ExtAlbumsListResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'albums': value['albums'] == null ? undefined : ((value['albums'] as Array<any>).map(ExtAlbumReadDtoToJSON)),
        'count': value['count'],
        'total': value['total'],
    };
}

