/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtAssetReadDto
 */
export interface ExtAssetReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtAssetReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtAssetReadDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtAssetReadDto
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtAssetReadDto
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtAssetReadDto
     */
    url?: string;
}

/**
 * Check if a given object implements the ExtAssetReadDto interface.
 */
export function instanceOfExtAssetReadDto(value: object): boolean {
    return true;
}

export function ExtAssetReadDtoFromJSON(json: any): ExtAssetReadDto {
    return ExtAssetReadDtoFromJSONTyped(json, false);
}

export function ExtAssetReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtAssetReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'mime': json['mime'] == null ? undefined : json['mime'],
        'size': json['size'] == null ? undefined : json['size'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ExtAssetReadDtoToJSON(value?: ExtAssetReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'mime': value['mime'],
        'size': value['size'],
        'url': value['url'],
    };
}

