/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtCircleWriteDto
 */
export interface ExtCircleWriteDto {
    /**
     * 
     * @type {string}
     * @memberof ExtCircleWriteDto
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtCircleWriteDto
     */
    alias?: Array<string>;
}

/**
 * Check if a given object implements the ExtCircleWriteDto interface.
 */
export function instanceOfExtCircleWriteDto(value: object): boolean {
    return true;
}

export function ExtCircleWriteDtoFromJSON(json: any): ExtCircleWriteDto {
    return ExtCircleWriteDtoFromJSONTyped(json, false);
}

export function ExtCircleWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtCircleWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'alias': json['alias'] == null ? undefined : json['alias'],
    };
}

export function ExtCircleWriteDtoToJSON(value?: ExtCircleWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'alias': value['alias'],
    };
}

