/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtCircleWebsiteReadDto
 */
export interface ExtCircleWebsiteReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtCircleWebsiteReadDto
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExtCircleWebsiteReadDto
     */
    invalid?: boolean;
}

/**
 * Check if a given object implements the ExtCircleWebsiteReadDto interface.
 */
export function instanceOfExtCircleWebsiteReadDto(value: object): boolean {
    return true;
}

export function ExtCircleWebsiteReadDtoFromJSON(json: any): ExtCircleWebsiteReadDto {
    return ExtCircleWebsiteReadDtoFromJSONTyped(json, false);
}

export function ExtCircleWebsiteReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtCircleWebsiteReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'invalid': json['invalid'] == null ? undefined : json['invalid'],
    };
}

export function ExtCircleWebsiteReadDtoToJSON(value?: ExtCircleWebsiteReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'invalid': value['invalid'],
    };
}

