/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExtCircleStatus = {
    Active: 'Active',
    Inactive: 'Inactive',
    Disbanded: 'Disbanded',
    Transfer: 'Transfer',
    Unknown: 'Unknown',
    Unset: 'Unset'
} as const;
export type ExtCircleStatus = typeof ExtCircleStatus[keyof typeof ExtCircleStatus];


export function ExtCircleStatusFromJSON(json: any): ExtCircleStatus {
    return ExtCircleStatusFromJSONTyped(json, false);
}

export function ExtCircleStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtCircleStatus {
    return json as ExtCircleStatus;
}

export function ExtCircleStatusToJSON(value?: ExtCircleStatus | null): any {
    return value as any;
}

