/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtHlsPlaylistType } from './ExtHlsPlaylistType';
import {
    ExtHlsPlaylistTypeFromJSON,
    ExtHlsPlaylistTypeFromJSONTyped,
    ExtHlsPlaylistTypeToJSON,
} from './ExtHlsPlaylistType';

/**
 * 
 * @export
 * @interface ExtHlsPlaylistWriteDto
 */
export interface ExtHlsPlaylistWriteDto {
    /**
     * 
     * @type {string}
     * @memberof ExtHlsPlaylistWriteDto
     */
    id?: string;
    /**
     * 
     * @type {ExtHlsPlaylistType}
     * @memberof ExtHlsPlaylistWriteDto
     */
    type?: ExtHlsPlaylistType;
    /**
     * 
     * @type {number}
     * @memberof ExtHlsPlaylistWriteDto
     */
    bitrate?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtHlsPlaylistWriteDto
     */
    hlsPlaylistPath?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtHlsPlaylistWriteDto
     */
    trackId?: string;
}

/**
 * Check if a given object implements the ExtHlsPlaylistWriteDto interface.
 */
export function instanceOfExtHlsPlaylistWriteDto(value: object): boolean {
    return true;
}

export function ExtHlsPlaylistWriteDtoFromJSON(json: any): ExtHlsPlaylistWriteDto {
    return ExtHlsPlaylistWriteDtoFromJSONTyped(json, false);
}

export function ExtHlsPlaylistWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtHlsPlaylistWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : ExtHlsPlaylistTypeFromJSON(json['type']),
        'bitrate': json['bitrate'] == null ? undefined : json['bitrate'],
        'hlsPlaylistPath': json['hlsPlaylistPath'] == null ? undefined : json['hlsPlaylistPath'],
        'trackId': json['trackId'] == null ? undefined : json['trackId'],
    };
}

export function ExtHlsPlaylistWriteDtoToJSON(value?: ExtHlsPlaylistWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': ExtHlsPlaylistTypeToJSON(value['type']),
        'bitrate': value['bitrate'],
        'hlsPlaylistPath': value['hlsPlaylistPath'],
        'trackId': value['trackId'],
    };
}

