/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExtHlsPlaylistType = {
    Master: 'Master',
    Media: 'Media'
} as const;
export type ExtHlsPlaylistType = typeof ExtHlsPlaylistType[keyof typeof ExtHlsPlaylistType];


export function ExtHlsPlaylistTypeFromJSON(json: any): ExtHlsPlaylistType {
    return ExtHlsPlaylistTypeFromJSONTyped(json, false);
}

export function ExtHlsPlaylistTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtHlsPlaylistType {
    return json as ExtHlsPlaylistType;
}

export function ExtHlsPlaylistTypeToJSON(value?: ExtHlsPlaylistType | null): any {
    return value as any;
}

