/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtRubyDto } from './ExtRubyDto';
import {
    ExtRubyDtoFromJSON,
    ExtRubyDtoFromJSONTyped,
    ExtRubyDtoToJSON,
} from './ExtRubyDto';

/**
 * 
 * @export
 * @interface ExtLyricsTextDto
 */
export interface ExtLyricsTextDto {
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsTextDto
     */
    lang?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsTextDto
     */
    text?: string;
    /**
     * 
     * @type {Array<ExtRubyDto>}
     * @memberof ExtLyricsTextDto
     */
    ruby?: Array<ExtRubyDto>;
}

/**
 * Check if a given object implements the ExtLyricsTextDto interface.
 */
export function instanceOfExtLyricsTextDto(value: object): boolean {
    return true;
}

export function ExtLyricsTextDtoFromJSON(json: any): ExtLyricsTextDto {
    return ExtLyricsTextDtoFromJSONTyped(json, false);
}

export function ExtLyricsTextDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyricsTextDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lang': json['lang'] == null ? undefined : json['lang'],
        'text': json['text'] == null ? undefined : json['text'],
        'ruby': json['ruby'] == null ? undefined : ((json['ruby'] as Array<any>).map(ExtRubyDtoFromJSON)),
    };
}

export function ExtLyricsTextDtoToJSON(value?: ExtLyricsTextDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lang': value['lang'],
        'text': value['text'],
        'ruby': value['ruby'] == null ? undefined : ((value['ruby'] as Array<any>).map(ExtRubyDtoToJSON)),
    };
}

