/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLyricsVariantDto } from './ExtLyricsVariantDto';
import {
    ExtLyricsVariantDtoFromJSON,
    ExtLyricsVariantDtoFromJSONTyped,
    ExtLyricsVariantDtoToJSON,
} from './ExtLyricsVariantDto';

/**
 * 
 * @export
 * @interface ExtLyricsReadDto
 */
export interface ExtLyricsReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsReadDto
     */
    id?: string;
    /**
     * 
     * @type {Array<ExtLyricsVariantDto>}
     * @memberof ExtLyricsReadDto
     */
    variants?: Array<ExtLyricsVariantDto>;
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsReadDto
     */
    referenceUrl?: string;
}

/**
 * Check if a given object implements the ExtLyricsReadDto interface.
 */
export function instanceOfExtLyricsReadDto(value: object): boolean {
    return true;
}

export function ExtLyricsReadDtoFromJSON(json: any): ExtLyricsReadDto {
    return ExtLyricsReadDtoFromJSONTyped(json, false);
}

export function ExtLyricsReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyricsReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'variants': json['variants'] == null ? undefined : ((json['variants'] as Array<any>).map(ExtLyricsVariantDtoFromJSON)),
        'referenceUrl': json['referenceUrl'] == null ? undefined : json['referenceUrl'],
    };
}

export function ExtLyricsReadDtoToJSON(value?: ExtLyricsReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'variants': value['variants'] == null ? undefined : ((value['variants'] as Array<any>).map(ExtLyricsVariantDtoToJSON)),
        'referenceUrl': value['referenceUrl'],
    };
}

