/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLyricsLineDto } from './ExtLyricsLineDto';
import {
    ExtLyricsLineDtoFromJSON,
    ExtLyricsLineDtoFromJSONTyped,
    ExtLyricsLineDtoToJSON,
} from './ExtLyricsLineDto';

/**
 * 
 * @export
 * @interface ExtLyricsVariantDto
 */
export interface ExtLyricsVariantDto {
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsVariantDto
     */
    variant?: string;
    /**
     * 
     * @type {Array<ExtLyricsLineDto>}
     * @memberof ExtLyricsVariantDto
     */
    lines?: Array<ExtLyricsLineDto>;
}

/**
 * Check if a given object implements the ExtLyricsVariantDto interface.
 */
export function instanceOfExtLyricsVariantDto(value: object): boolean {
    return true;
}

export function ExtLyricsVariantDtoFromJSON(json: any): ExtLyricsVariantDto {
    return ExtLyricsVariantDtoFromJSONTyped(json, false);
}

export function ExtLyricsVariantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyricsVariantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'variant': json['variant'] == null ? undefined : json['variant'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(ExtLyricsLineDtoFromJSON)),
    };
}

export function ExtLyricsVariantDtoToJSON(value?: ExtLyricsVariantDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'variant': value['variant'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(ExtLyricsLineDtoToJSON)),
    };
}

