/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLyricsVariant } from './ExtLyricsVariant';
import {
    ExtLyricsVariantFromJSON,
    ExtLyricsVariantFromJSONTyped,
    ExtLyricsVariantToJSON,
} from './ExtLyricsVariant';

/**
 * 
 * @export
 * @interface ExtLyrics
 */
export interface ExtLyrics {
    /**
     * 
     * @type {string}
     * @memberof ExtLyrics
     */
    id: string;
    /**
     * 
     * @type {Array<ExtLyricsVariant>}
     * @memberof ExtLyrics
     */
    variants: Array<ExtLyricsVariant> | null;
    /**
     * 
     * @type {string}
     * @memberof ExtLyrics
     */
    referenceUrl?: string;
}

/**
 * Check if a given object implements the ExtLyrics interface.
 */
export function instanceOfExtLyrics(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('variants' in value)) return false;
    return true;
}

export function ExtLyricsFromJSON(json: any): ExtLyrics {
    return ExtLyricsFromJSONTyped(json, false);
}

export function ExtLyricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyrics {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'variants': (json['variants'] == null ? null : (json['variants'] as Array<any>).map(ExtLyricsVariantFromJSON)),
        'referenceUrl': json['referenceUrl'] == null ? undefined : json['referenceUrl'],
    };
}

export function ExtLyricsToJSON(value?: ExtLyrics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'variants': (value['variants'] == null ? null : (value['variants'] as Array<any>).map(ExtLyricsVariantToJSON)),
        'referenceUrl': value['referenceUrl'],
    };
}

