/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLyricsText } from './ExtLyricsText';
import {
    ExtLyricsTextFromJSON,
    ExtLyricsTextFromJSONTyped,
    ExtLyricsTextToJSON,
} from './ExtLyricsText';

/**
 * 
 * @export
 * @interface ExtLyricsLine
 */
export interface ExtLyricsLine {
    /**
     * 
     * @type {number}
     * @memberof ExtLyricsLine
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsLine
     */
    time?: string;
    /**
     * 
     * @type {Array<ExtLyricsText>}
     * @memberof ExtLyricsLine
     */
    blocks: Array<ExtLyricsText> | null;
}

/**
 * Check if a given object implements the ExtLyricsLine interface.
 */
export function instanceOfExtLyricsLine(value: object): boolean {
    if (!('index' in value)) return false;
    if (!('blocks' in value)) return false;
    return true;
}

export function ExtLyricsLineFromJSON(json: any): ExtLyricsLine {
    return ExtLyricsLineFromJSONTyped(json, false);
}

export function ExtLyricsLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyricsLine {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'time': json['time'] == null ? undefined : json['time'],
        'blocks': (json['blocks'] == null ? null : (json['blocks'] as Array<any>).map(ExtLyricsTextFromJSON)),
    };
}

export function ExtLyricsLineToJSON(value?: ExtLyricsLine | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'time': value['time'],
        'blocks': (value['blocks'] == null ? null : (value['blocks'] as Array<any>).map(ExtLyricsTextToJSON)),
    };
}

