/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLyricsLine } from './ExtLyricsLine';
import {
    ExtLyricsLineFromJSON,
    ExtLyricsLineFromJSONTyped,
    ExtLyricsLineToJSON,
} from './ExtLyricsLine';

/**
 * 
 * @export
 * @interface ExtLyricsVariant
 */
export interface ExtLyricsVariant {
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsVariant
     */
    variant?: string;
    /**
     * 
     * @type {Array<ExtLyricsLine>}
     * @memberof ExtLyricsVariant
     */
    lines: Array<ExtLyricsLine> | null;
}

/**
 * Check if a given object implements the ExtLyricsVariant interface.
 */
export function instanceOfExtLyricsVariant(value: object): boolean {
    if (!('lines' in value)) return false;
    return true;
}

export function ExtLyricsVariantFromJSON(json: any): ExtLyricsVariant {
    return ExtLyricsVariantFromJSONTyped(json, false);
}

export function ExtLyricsVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyricsVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'variant': json['variant'] == null ? undefined : json['variant'],
        'lines': (json['lines'] == null ? null : (json['lines'] as Array<any>).map(ExtLyricsLineFromJSON)),
    };
}

export function ExtLyricsVariantToJSON(value?: ExtLyricsVariant | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'variant': value['variant'],
        'lines': (value['lines'] == null ? null : (value['lines'] as Array<any>).map(ExtLyricsLineToJSON)),
    };
}

