/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLyricsTextDto } from './ExtLyricsTextDto';
import {
    ExtLyricsTextDtoFromJSON,
    ExtLyricsTextDtoFromJSONTyped,
    ExtLyricsTextDtoToJSON,
} from './ExtLyricsTextDto';

/**
 * 
 * @export
 * @interface ExtLyricsLineDto
 */
export interface ExtLyricsLineDto {
    /**
     * 
     * @type {number}
     * @memberof ExtLyricsLineDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtLyricsLineDto
     */
    time?: string;
    /**
     * 
     * @type {Array<ExtLyricsTextDto>}
     * @memberof ExtLyricsLineDto
     */
    blocks?: Array<ExtLyricsTextDto>;
}

/**
 * Check if a given object implements the ExtLyricsLineDto interface.
 */
export function instanceOfExtLyricsLineDto(value: object): boolean {
    return true;
}

export function ExtLyricsLineDtoFromJSON(json: any): ExtLyricsLineDto {
    return ExtLyricsLineDtoFromJSONTyped(json, false);
}

export function ExtLyricsLineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtLyricsLineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'time': json['time'] == null ? undefined : json['time'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(ExtLyricsTextDtoFromJSON)),
    };
}

export function ExtLyricsLineDtoToJSON(value?: ExtLyricsLineDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'time': value['time'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(ExtLyricsTextDtoToJSON)),
    };
}

