/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtOriginalAlbumReadDto } from './ExtOriginalAlbumReadDto';
import {
    ExtOriginalAlbumReadDtoFromJSON,
    ExtOriginalAlbumReadDtoFromJSONTyped,
    ExtOriginalAlbumReadDtoToJSON,
} from './ExtOriginalAlbumReadDto';

/**
 * 
 * @export
 * @interface ExtOriginalAlbumReadDtoActionResult
 */
export interface ExtOriginalAlbumReadDtoActionResult {
    /**
     * 
     * @type {object}
     * @memberof ExtOriginalAlbumReadDtoActionResult
     */
    result?: object;
    /**
     * 
     * @type {ExtOriginalAlbumReadDto}
     * @memberof ExtOriginalAlbumReadDtoActionResult
     */
    value?: ExtOriginalAlbumReadDto;
}

/**
 * Check if a given object implements the ExtOriginalAlbumReadDtoActionResult interface.
 */
export function instanceOfExtOriginalAlbumReadDtoActionResult(value: object): boolean {
    return true;
}

export function ExtOriginalAlbumReadDtoActionResultFromJSON(json: any): ExtOriginalAlbumReadDtoActionResult {
    return ExtOriginalAlbumReadDtoActionResultFromJSONTyped(json, false);
}

export function ExtOriginalAlbumReadDtoActionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOriginalAlbumReadDtoActionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'value': json['value'] == null ? undefined : ExtOriginalAlbumReadDtoFromJSON(json['value']),
    };
}

export function ExtOriginalAlbumReadDtoActionResultToJSON(value?: ExtOriginalAlbumReadDtoActionResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'result': value['result'],
        'value': ExtOriginalAlbumReadDtoToJSON(value['value']),
    };
}

