/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtOperation
 */
export interface ExtOperation {
    /**
     * 
     * @type {any}
     * @memberof ExtOperation
     */
    value?: any;
    /**
     * 
     * @type {string}
     * @memberof ExtOperation
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtOperation
     */
    op?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtOperation
     */
    from?: string;
}

/**
 * Check if a given object implements the ExtOperation interface.
 */
export function instanceOfExtOperation(value: object): boolean {
    return true;
}

export function ExtOperationFromJSON(json: any): ExtOperation {
    return ExtOperationFromJSONTyped(json, false);
}

export function ExtOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'path': json['path'] == null ? undefined : json['path'],
        'op': json['op'] == null ? undefined : json['op'],
        'from': json['from'] == null ? undefined : json['from'],
    };
}

export function ExtOperationToJSON(value?: ExtOperation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
        'path': value['path'],
        'op': value['op'],
        'from': value['from'],
    };
}

