/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';

/**
 * 
 * @export
 * @interface ExtOriginalAlbumWriteDto
 */
export interface ExtOriginalAlbumWriteDto {
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalAlbumWriteDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalAlbumWriteDto
     */
    type: string;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtOriginalAlbumWriteDto
     */
    fullName: ExtLocalizedField;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtOriginalAlbumWriteDto
     */
    shortName: ExtLocalizedField;
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalAlbumWriteDto
     */
    externalReference?: string;
}

/**
 * Check if a given object implements the ExtOriginalAlbumWriteDto interface.
 */
export function instanceOfExtOriginalAlbumWriteDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('type' in value)) return false;
    if (!('fullName' in value)) return false;
    if (!('shortName' in value)) return false;
    return true;
}

export function ExtOriginalAlbumWriteDtoFromJSON(json: any): ExtOriginalAlbumWriteDto {
    return ExtOriginalAlbumWriteDtoFromJSONTyped(json, false);
}

export function ExtOriginalAlbumWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOriginalAlbumWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'fullName': ExtLocalizedFieldFromJSON(json['fullName']),
        'shortName': ExtLocalizedFieldFromJSON(json['shortName']),
        'externalReference': json['externalReference'] == null ? undefined : json['externalReference'],
    };
}

export function ExtOriginalAlbumWriteDtoToJSON(value?: ExtOriginalAlbumWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'fullName': ExtLocalizedFieldToJSON(value['fullName']),
        'shortName': ExtLocalizedFieldToJSON(value['shortName']),
        'externalReference': value['externalReference'],
    };
}

