/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';
import type { ExtOriginalAlbumReadDto } from './ExtOriginalAlbumReadDto';
import {
    ExtOriginalAlbumReadDtoFromJSON,
    ExtOriginalAlbumReadDtoFromJSONTyped,
    ExtOriginalAlbumReadDtoToJSON,
} from './ExtOriginalAlbumReadDto';

/**
 * 
 * @export
 * @interface ExtOriginalTrackReadDto
 */
export interface ExtOriginalTrackReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalTrackReadDto
     */
    id?: string;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtOriginalTrackReadDto
     */
    title?: ExtLocalizedField;
    /**
     * 
     * @type {ExtOriginalAlbumReadDto}
     * @memberof ExtOriginalTrackReadDto
     */
    album?: ExtOriginalAlbumReadDto;
}

/**
 * Check if a given object implements the ExtOriginalTrackReadDto interface.
 */
export function instanceOfExtOriginalTrackReadDto(value: object): boolean {
    return true;
}

export function ExtOriginalTrackReadDtoFromJSON(json: any): ExtOriginalTrackReadDto {
    return ExtOriginalTrackReadDtoFromJSONTyped(json, false);
}

export function ExtOriginalTrackReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOriginalTrackReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : ExtLocalizedFieldFromJSON(json['title']),
        'album': json['album'] == null ? undefined : ExtOriginalAlbumReadDtoFromJSON(json['album']),
    };
}

export function ExtOriginalTrackReadDtoToJSON(value?: ExtOriginalTrackReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': ExtLocalizedFieldToJSON(value['title']),
        'album': ExtOriginalAlbumReadDtoToJSON(value['album']),
    };
}

