/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';

/**
 * 
 * @export
 * @interface ExtOriginalAlbumReadDto
 */
export interface ExtOriginalAlbumReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalAlbumReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalAlbumReadDto
     */
    type?: string;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtOriginalAlbumReadDto
     */
    fullName?: ExtLocalizedField;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtOriginalAlbumReadDto
     */
    shortName?: ExtLocalizedField;
}

/**
 * Check if a given object implements the ExtOriginalAlbumReadDto interface.
 */
export function instanceOfExtOriginalAlbumReadDto(value: object): boolean {
    return true;
}

export function ExtOriginalAlbumReadDtoFromJSON(json: any): ExtOriginalAlbumReadDto {
    return ExtOriginalAlbumReadDtoFromJSONTyped(json, false);
}

export function ExtOriginalAlbumReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOriginalAlbumReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'fullName': json['fullName'] == null ? undefined : ExtLocalizedFieldFromJSON(json['fullName']),
        'shortName': json['shortName'] == null ? undefined : ExtLocalizedFieldFromJSON(json['shortName']),
    };
}

export function ExtOriginalAlbumReadDtoToJSON(value?: ExtOriginalAlbumReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'fullName': ExtLocalizedFieldToJSON(value['fullName']),
        'shortName': ExtLocalizedFieldToJSON(value['shortName']),
    };
}

