/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtOriginalTrackReadDto } from './ExtOriginalTrackReadDto';
import {
    ExtOriginalTrackReadDtoFromJSON,
    ExtOriginalTrackReadDtoFromJSONTyped,
    ExtOriginalTrackReadDtoToJSON,
} from './ExtOriginalTrackReadDto';

/**
 * 
 * @export
 * @interface ExtOriginalTrackReadDtoActionResult
 */
export interface ExtOriginalTrackReadDtoActionResult {
    /**
     * 
     * @type {object}
     * @memberof ExtOriginalTrackReadDtoActionResult
     */
    result?: object;
    /**
     * 
     * @type {ExtOriginalTrackReadDto}
     * @memberof ExtOriginalTrackReadDtoActionResult
     */
    value?: ExtOriginalTrackReadDto;
}

/**
 * Check if a given object implements the ExtOriginalTrackReadDtoActionResult interface.
 */
export function instanceOfExtOriginalTrackReadDtoActionResult(value: object): boolean {
    return true;
}

export function ExtOriginalTrackReadDtoActionResultFromJSON(json: any): ExtOriginalTrackReadDtoActionResult {
    return ExtOriginalTrackReadDtoActionResultFromJSONTyped(json, false);
}

export function ExtOriginalTrackReadDtoActionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOriginalTrackReadDtoActionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'value': json['value'] == null ? undefined : ExtOriginalTrackReadDtoFromJSON(json['value']),
    };
}

export function ExtOriginalTrackReadDtoActionResultToJSON(value?: ExtOriginalTrackReadDtoActionResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'result': value['result'],
        'value': ExtOriginalTrackReadDtoToJSON(value['value']),
    };
}

