/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';

/**
 * 
 * @export
 * @interface ExtOriginalTrackWriteDto
 */
export interface ExtOriginalTrackWriteDto {
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalTrackWriteDto
     */
    id: string;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtOriginalTrackWriteDto
     */
    title: ExtLocalizedField;
    /**
     * 
     * @type {string}
     * @memberof ExtOriginalTrackWriteDto
     */
    externalReference?: string;
}

/**
 * Check if a given object implements the ExtOriginalTrackWriteDto interface.
 */
export function instanceOfExtOriginalTrackWriteDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function ExtOriginalTrackWriteDtoFromJSON(json: any): ExtOriginalTrackWriteDto {
    return ExtOriginalTrackWriteDtoFromJSONTyped(json, false);
}

export function ExtOriginalTrackWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtOriginalTrackWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': ExtLocalizedFieldFromJSON(json['title']),
        'externalReference': json['externalReference'] == null ? undefined : json['externalReference'],
    };
}

export function ExtOriginalTrackWriteDtoToJSON(value?: ExtOriginalTrackWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': ExtLocalizedFieldToJSON(value['title']),
        'externalReference': value['externalReference'],
    };
}

