/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtPlaylistVisibility } from './ExtPlaylistVisibility';
import {
    ExtPlaylistVisibilityFromJSON,
    ExtPlaylistVisibilityFromJSONTyped,
    ExtPlaylistVisibilityToJSON,
} from './ExtPlaylistVisibility';

/**
 * 
 * @export
 * @interface ExtPlaylistInfo
 */
export interface ExtPlaylistInfo {
    /**
     * 
     * @type {string}
     * @memberof ExtPlaylistInfo
     */
    name?: string;
    /**
     * 
     * @type {ExtPlaylistVisibility}
     * @memberof ExtPlaylistInfo
     */
    visibility?: ExtPlaylistVisibility;
}

/**
 * Check if a given object implements the ExtPlaylistInfo interface.
 */
export function instanceOfExtPlaylistInfo(value: object): boolean {
    return true;
}

export function ExtPlaylistInfoFromJSON(json: any): ExtPlaylistInfo {
    return ExtPlaylistInfoFromJSONTyped(json, false);
}

export function ExtPlaylistInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtPlaylistInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'visibility': json['visibility'] == null ? undefined : ExtPlaylistVisibilityFromJSON(json['visibility']),
    };
}

export function ExtPlaylistInfoToJSON(value?: ExtPlaylistInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'visibility': ExtPlaylistVisibilityToJSON(value['visibility']),
    };
}

