/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExtPlaylistType = {
    Normal: 'Normal',
    Favorite: 'Favorite',
    History: 'History',
    Queue: 'Queue'
} as const;
export type ExtPlaylistType = typeof ExtPlaylistType[keyof typeof ExtPlaylistType];


export function ExtPlaylistTypeFromJSON(json: any): ExtPlaylistType {
    return ExtPlaylistTypeFromJSONTyped(json, false);
}

export function ExtPlaylistTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtPlaylistType {
    return json as ExtPlaylistType;
}

export function ExtPlaylistTypeToJSON(value?: ExtPlaylistType | null): any {
    return value as any;
}

