/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExtPlaylistVisibility = {
    Public: 'Public',
    Private: 'Private',
    Unlisted: 'Unlisted'
} as const;
export type ExtPlaylistVisibility = typeof ExtPlaylistVisibility[keyof typeof ExtPlaylistVisibility];


export function ExtPlaylistVisibilityFromJSON(json: any): ExtPlaylistVisibility {
    return ExtPlaylistVisibilityFromJSONTyped(json, false);
}

export function ExtPlaylistVisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtPlaylistVisibility {
    return json as ExtPlaylistVisibility;
}

export function ExtPlaylistVisibilityToJSON(value?: ExtPlaylistVisibility | null): any {
    return value as any;
}

