/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtPlaylistType } from './ExtPlaylistType';
import {
    ExtPlaylistTypeFromJSON,
    ExtPlaylistTypeFromJSONTyped,
    ExtPlaylistTypeToJSON,
} from './ExtPlaylistType';
import type { ExtPlaylistVisibility } from './ExtPlaylistVisibility';
import {
    ExtPlaylistVisibilityFromJSON,
    ExtPlaylistVisibilityFromJSONTyped,
    ExtPlaylistVisibilityToJSON,
} from './ExtPlaylistVisibility';
import type { ExtUserProfile } from './ExtUserProfile';
import {
    ExtUserProfileFromJSON,
    ExtUserProfileFromJSONTyped,
    ExtUserProfileToJSON,
} from './ExtUserProfile';

/**
 * 
 * @export
 * @interface ExtPlaylistReadDto
 */
export interface ExtPlaylistReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtPlaylistReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtPlaylistReadDto
     */
    name?: string;
    /**
     * 
     * @type {ExtUserProfile}
     * @memberof ExtPlaylistReadDto
     */
    owner?: ExtUserProfile;
    /**
     * 
     * @type {ExtPlaylistVisibility}
     * @memberof ExtPlaylistReadDto
     */
    visibility?: ExtPlaylistVisibility;
    /**
     * 
     * @type {ExtPlaylistType}
     * @memberof ExtPlaylistReadDto
     */
    type?: ExtPlaylistType;
    /**
     * 
     * @type {Date}
     * @memberof ExtPlaylistReadDto
     */
    lastModified?: Date;
}

/**
 * Check if a given object implements the ExtPlaylistReadDto interface.
 */
export function instanceOfExtPlaylistReadDto(value: object): boolean {
    return true;
}

export function ExtPlaylistReadDtoFromJSON(json: any): ExtPlaylistReadDto {
    return ExtPlaylistReadDtoFromJSONTyped(json, false);
}

export function ExtPlaylistReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtPlaylistReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'owner': json['owner'] == null ? undefined : ExtUserProfileFromJSON(json['owner']),
        'visibility': json['visibility'] == null ? undefined : ExtPlaylistVisibilityFromJSON(json['visibility']),
        'type': json['type'] == null ? undefined : ExtPlaylistTypeFromJSON(json['type']),
        'lastModified': json['lastModified'] == null ? undefined : (new Date(json['lastModified'])),
    };
}

export function ExtPlaylistReadDtoToJSON(value?: ExtPlaylistReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'owner': ExtUserProfileToJSON(value['owner']),
        'visibility': ExtPlaylistVisibilityToJSON(value['visibility']),
        'type': ExtPlaylistTypeToJSON(value['type']),
        'lastModified': value['lastModified'] == null ? undefined : ((value['lastModified']).toISOString()),
    };
}

