/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtRuby
 */
export interface ExtRuby {
    /**
     * 
     * @type {number}
     * @memberof ExtRuby
     */
    index: number;
    /**
     * 
     * @type {number}
     * @memberof ExtRuby
     */
    length: number;
    /**
     * 
     * @type {string}
     * @memberof ExtRuby
     */
    text: string | null;
}

/**
 * Check if a given object implements the ExtRuby interface.
 */
export function instanceOfExtRuby(value: object): boolean {
    if (!('index' in value)) return false;
    if (!('length' in value)) return false;
    if (!('text' in value)) return false;
    return true;
}

export function ExtRubyFromJSON(json: any): ExtRuby {
    return ExtRubyFromJSONTyped(json, false);
}

export function ExtRubyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtRuby {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'length': json['length'],
        'text': json['text'],
    };
}

export function ExtRubyToJSON(value?: ExtRuby | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'length': value['length'],
        'text': value['text'],
    };
}

