/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExtSortOrder = {
    Ascending: 'Ascending',
    Descending: 'Descending'
} as const;
export type ExtSortOrder = typeof ExtSortOrder[keyof typeof ExtSortOrder];


export function ExtSortOrderFromJSON(json: any): ExtSortOrder {
    return ExtSortOrderFromJSONTyped(json, false);
}

export function ExtSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtSortOrder {
    return json as ExtSortOrder;
}

export function ExtSortOrderToJSON(value?: ExtSortOrder | null): any {
    return value as any;
}

