/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtTrackUpdateDto
 */
export interface ExtTrackUpdateDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackUpdateDto
     */
    genre?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackUpdateDto
     */
    staff?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackUpdateDto
     */
    arrangement?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackUpdateDto
     */
    vocalist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackUpdateDto
     */
    lyricist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackUpdateDto
     */
    original?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ExtTrackUpdateDto
     */
    originalNonTouhou?: boolean;
}

/**
 * Check if a given object implements the ExtTrackUpdateDto interface.
 */
export function instanceOfExtTrackUpdateDto(value: object): boolean {
    return true;
}

export function ExtTrackUpdateDtoFromJSON(json: any): ExtTrackUpdateDto {
    return ExtTrackUpdateDtoFromJSONTyped(json, false);
}

export function ExtTrackUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtTrackUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'genre': json['genre'] == null ? undefined : json['genre'],
        'staff': json['staff'] == null ? undefined : json['staff'],
        'arrangement': json['arrangement'] == null ? undefined : json['arrangement'],
        'vocalist': json['vocalist'] == null ? undefined : json['vocalist'],
        'lyricist': json['lyricist'] == null ? undefined : json['lyricist'],
        'original': json['original'] == null ? undefined : json['original'],
        'originalNonTouhou': json['originalNonTouhou'] == null ? undefined : json['originalNonTouhou'],
    };
}

export function ExtTrackUpdateDtoToJSON(value?: ExtTrackUpdateDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'genre': value['genre'],
        'staff': value['staff'],
        'arrangement': value['arrangement'],
        'vocalist': value['vocalist'],
        'lyricist': value['lyricist'],
        'original': value['original'],
        'originalNonTouhou': value['originalNonTouhou'],
    };
}

