/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtAlbumReadDto } from './ExtAlbumReadDto';
import {
    ExtAlbumReadDtoFromJSON,
    ExtAlbumReadDtoFromJSONTyped,
    ExtAlbumReadDtoToJSON,
} from './ExtAlbumReadDto';
import type { ExtAssetReadDto } from './ExtAssetReadDto';
import {
    ExtAssetReadDtoFromJSON,
    ExtAssetReadDtoFromJSONTyped,
    ExtAssetReadDtoToJSON,
} from './ExtAssetReadDto';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';
import type { ExtOriginalTrackReadDto } from './ExtOriginalTrackReadDto';
import {
    ExtOriginalTrackReadDtoFromJSON,
    ExtOriginalTrackReadDtoFromJSONTyped,
    ExtOriginalTrackReadDtoToJSON,
} from './ExtOriginalTrackReadDto';

/**
 * 
 * @export
 * @interface ExtTrackReadDto
 */
export interface ExtTrackReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtTrackReadDto
     */
    id?: string;
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtTrackReadDto
     */
    name?: ExtLocalizedField;
    /**
     * 
     * @type {number}
     * @memberof ExtTrackReadDto
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtTrackReadDto
     */
    disc?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtTrackReadDto
     */
    duration?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackReadDto
     */
    genre?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackReadDto
     */
    staff?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackReadDto
     */
    arrangement?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackReadDto
     */
    vocalist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackReadDto
     */
    lyricist?: Array<string>;
    /**
     * 
     * @type {Array<ExtOriginalTrackReadDto>}
     * @memberof ExtTrackReadDto
     */
    original?: Array<ExtOriginalTrackReadDto>;
    /**
     * 
     * @type {boolean}
     * @memberof ExtTrackReadDto
     */
    originalNonTouhou?: boolean;
    /**
     * 
     * @type {ExtAlbumReadDto}
     * @memberof ExtTrackReadDto
     */
    album?: ExtAlbumReadDto;
    /**
     * 
     * @type {ExtAssetReadDto}
     * @memberof ExtTrackReadDto
     */
    trackFile?: ExtAssetReadDto;
    /**
     * 
     * @type {boolean}
     * @memberof ExtTrackReadDto
     */
    hasLyrics?: boolean;
}

/**
 * Check if a given object implements the ExtTrackReadDto interface.
 */
export function instanceOfExtTrackReadDto(value: object): boolean {
    return true;
}

export function ExtTrackReadDtoFromJSON(json: any): ExtTrackReadDto {
    return ExtTrackReadDtoFromJSONTyped(json, false);
}

export function ExtTrackReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtTrackReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : ExtLocalizedFieldFromJSON(json['name']),
        'index': json['index'] == null ? undefined : json['index'],
        'disc': json['disc'] == null ? undefined : json['disc'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'staff': json['staff'] == null ? undefined : json['staff'],
        'arrangement': json['arrangement'] == null ? undefined : json['arrangement'],
        'vocalist': json['vocalist'] == null ? undefined : json['vocalist'],
        'lyricist': json['lyricist'] == null ? undefined : json['lyricist'],
        'original': json['original'] == null ? undefined : ((json['original'] as Array<any>).map(ExtOriginalTrackReadDtoFromJSON)),
        'originalNonTouhou': json['originalNonTouhou'] == null ? undefined : json['originalNonTouhou'],
        'album': json['album'] == null ? undefined : ExtAlbumReadDtoFromJSON(json['album']),
        'trackFile': json['trackFile'] == null ? undefined : ExtAssetReadDtoFromJSON(json['trackFile']),
        'hasLyrics': json['hasLyrics'] == null ? undefined : json['hasLyrics'],
    };
}

export function ExtTrackReadDtoToJSON(value?: ExtTrackReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': ExtLocalizedFieldToJSON(value['name']),
        'index': value['index'],
        'disc': value['disc'],
        'duration': value['duration'],
        'genre': value['genre'],
        'staff': value['staff'],
        'arrangement': value['arrangement'],
        'vocalist': value['vocalist'],
        'lyricist': value['lyricist'],
        'original': value['original'] == null ? undefined : ((value['original'] as Array<any>).map(ExtOriginalTrackReadDtoToJSON)),
        'originalNonTouhou': value['originalNonTouhou'],
        'album': ExtAlbumReadDtoToJSON(value['album']),
        'trackFile': ExtAssetReadDtoToJSON(value['trackFile']),
        'hasLyrics': value['hasLyrics'],
    };
}

