/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExtTrackOrderOptions = {
    Id: 'Id',
    Date: 'Date',
    Title: 'Title',
    Duration: 'Duration',
    AlbumId: 'AlbumId',
    AlbumTitle: 'AlbumTitle'
} as const;
export type ExtTrackOrderOptions = typeof ExtTrackOrderOptions[keyof typeof ExtTrackOrderOptions];


export function ExtTrackOrderOptionsFromJSON(json: any): ExtTrackOrderOptions {
    return ExtTrackOrderOptionsFromJSONTyped(json, false);
}

export function ExtTrackOrderOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtTrackOrderOptions {
    return json as ExtTrackOrderOptions;
}

export function ExtTrackOrderOptionsToJSON(value?: ExtTrackOrderOptions | null): any {
    return value as any;
}

