/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtTrackReadDto } from './ExtTrackReadDto';
import {
    ExtTrackReadDtoFromJSON,
    ExtTrackReadDtoFromJSONTyped,
    ExtTrackReadDtoToJSON,
} from './ExtTrackReadDto';

/**
 * 
 * @export
 * @interface ExtTrackGetMultipleResp
 */
export interface ExtTrackGetMultipleResp {
    /**
     * 
     * @type {Array<ExtTrackReadDto>}
     * @memberof ExtTrackGetMultipleResp
     */
    tracks?: Array<ExtTrackReadDto>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackGetMultipleResp
     */
    notFound?: Array<string>;
}

/**
 * Check if a given object implements the ExtTrackGetMultipleResp interface.
 */
export function instanceOfExtTrackGetMultipleResp(value: object): boolean {
    return true;
}

export function ExtTrackGetMultipleRespFromJSON(json: any): ExtTrackGetMultipleResp {
    return ExtTrackGetMultipleRespFromJSONTyped(json, false);
}

export function ExtTrackGetMultipleRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtTrackGetMultipleResp {
    if (json == null) {
        return json;
    }
    return {
        
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(ExtTrackReadDtoFromJSON)),
        'notFound': json['notFound'] == null ? undefined : json['notFound'],
    };
}

export function ExtTrackGetMultipleRespToJSON(value?: ExtTrackGetMultipleResp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(ExtTrackReadDtoToJSON)),
        'notFound': value['notFound'],
    };
}

