/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtLocalizedField } from './ExtLocalizedField';
import {
    ExtLocalizedFieldFromJSON,
    ExtLocalizedFieldFromJSONTyped,
    ExtLocalizedFieldToJSON,
} from './ExtLocalizedField';

/**
 * 
 * @export
 * @interface ExtTrackWriteDto
 */
export interface ExtTrackWriteDto {
    /**
     * 
     * @type {ExtLocalizedField}
     * @memberof ExtTrackWriteDto
     */
    name: ExtLocalizedField;
    /**
     * 
     * @type {number}
     * @memberof ExtTrackWriteDto
     */
    index: number;
    /**
     * 
     * @type {number}
     * @memberof ExtTrackWriteDto
     */
    disc: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackWriteDto
     */
    genre?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackWriteDto
     */
    staff?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackWriteDto
     */
    arrangement?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackWriteDto
     */
    vocalist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackWriteDto
     */
    lyricist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtTrackWriteDto
     */
    original?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ExtTrackWriteDto
     */
    originalNonTouhou?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExtTrackWriteDto
     */
    trackFile?: string;
}

/**
 * Check if a given object implements the ExtTrackWriteDto interface.
 */
export function instanceOfExtTrackWriteDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('index' in value)) return false;
    if (!('disc' in value)) return false;
    return true;
}

export function ExtTrackWriteDtoFromJSON(json: any): ExtTrackWriteDto {
    return ExtTrackWriteDtoFromJSONTyped(json, false);
}

export function ExtTrackWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtTrackWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': ExtLocalizedFieldFromJSON(json['name']),
        'index': json['index'],
        'disc': json['disc'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'staff': json['staff'] == null ? undefined : json['staff'],
        'arrangement': json['arrangement'] == null ? undefined : json['arrangement'],
        'vocalist': json['vocalist'] == null ? undefined : json['vocalist'],
        'lyricist': json['lyricist'] == null ? undefined : json['lyricist'],
        'original': json['original'] == null ? undefined : json['original'],
        'originalNonTouhou': json['originalNonTouhou'] == null ? undefined : json['originalNonTouhou'],
        'trackFile': json['trackFile'] == null ? undefined : json['trackFile'],
    };
}

export function ExtTrackWriteDtoToJSON(value?: ExtTrackWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': ExtLocalizedFieldToJSON(value['name']),
        'index': value['index'],
        'disc': value['disc'],
        'genre': value['genre'],
        'staff': value['staff'],
        'arrangement': value['arrangement'],
        'vocalist': value['vocalist'],
        'lyricist': value['lyricist'],
        'original': value['original'],
        'originalNonTouhou': value['originalNonTouhou'],
        'trackFile': value['trackFile'],
    };
}

