/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtTrackReadDto } from './ExtTrackReadDto';
import {
    ExtTrackReadDtoFromJSON,
    ExtTrackReadDtoFromJSONTyped,
    ExtTrackReadDtoToJSON,
} from './ExtTrackReadDto';

/**
 * 
 * @export
 * @interface ExtTrackListResult
 */
export interface ExtTrackListResult {
    /**
     * 
     * @type {Array<ExtTrackReadDto>}
     * @memberof ExtTrackListResult
     */
    tracks?: Array<ExtTrackReadDto>;
    /**
     * 
     * @type {number}
     * @memberof ExtTrackListResult
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtTrackListResult
     */
    total?: number;
}

/**
 * Check if a given object implements the ExtTrackListResult interface.
 */
export function instanceOfExtTrackListResult(value: object): boolean {
    return true;
}

export function ExtTrackListResultFromJSON(json: any): ExtTrackListResult {
    return ExtTrackListResultFromJSONTyped(json, false);
}

export function ExtTrackListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtTrackListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(ExtTrackReadDtoFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ExtTrackListResultToJSON(value?: ExtTrackListResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(ExtTrackReadDtoToJSON)),
        'count': value['count'],
        'total': value['total'],
    };
}

