/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtUserProfileReadDto
 */
export interface ExtUserProfileReadDto {
    /**
     * 
     * @type {string}
     * @memberof ExtUserProfileReadDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtUserProfileReadDto
     */
    displayName?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExtUserProfileReadDto
     */
    dateJoined?: Date;
}

/**
 * Check if a given object implements the ExtUserProfileReadDto interface.
 */
export function instanceOfExtUserProfileReadDto(value: object): boolean {
    return true;
}

export function ExtUserProfileReadDtoFromJSON(json: any): ExtUserProfileReadDto {
    return ExtUserProfileReadDtoFromJSONTyped(json, false);
}

export function ExtUserProfileReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtUserProfileReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'dateJoined': json['dateJoined'] == null ? undefined : (new Date(json['dateJoined'])),
    };
}

export function ExtUserProfileReadDtoToJSON(value?: ExtUserProfileReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'dateJoined': value['dateJoined'] == null ? undefined : ((value['dateJoined']).toISOString()),
    };
}

