/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtUserProfileWriteDto
 */
export interface ExtUserProfileWriteDto {
    /**
     * 
     * @type {string}
     * @memberof ExtUserProfileWriteDto
     */
    displayName: string;
}

/**
 * Check if a given object implements the ExtUserProfileWriteDto interface.
 */
export function instanceOfExtUserProfileWriteDto(value: object): boolean {
    if (!('displayName' in value)) return false;
    return true;
}

export function ExtUserProfileWriteDtoFromJSON(json: any): ExtUserProfileWriteDto {
    return ExtUserProfileWriteDtoFromJSONTyped(json, false);
}

export function ExtUserProfileWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtUserProfileWriteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'],
    };
}

export function ExtUserProfileWriteDtoToJSON(value?: ExtUserProfileWriteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
    };
}

