/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RubyDto } from './RubyDto';
import {
    RubyDtoFromJSON,
    RubyDtoFromJSONTyped,
    RubyDtoToJSON,
} from './RubyDto';

/**
 * 
 * @export
 * @interface LyricsTextDto
 */
export interface LyricsTextDto {
    /**
     * 
     * @type {string}
     * @memberof LyricsTextDto
     */
    lang?: string;
    /**
     * 
     * @type {string}
     * @memberof LyricsTextDto
     */
    text?: string;
    /**
     * 
     * @type {Array<RubyDto>}
     * @memberof LyricsTextDto
     */
    ruby?: Array<RubyDto>;
}

/**
 * Check if a given object implements the LyricsTextDto interface.
 */
export function instanceOfLyricsTextDto(value: object): boolean {
    return true;
}

export function LyricsTextDtoFromJSON(json: any): LyricsTextDto {
    return LyricsTextDtoFromJSONTyped(json, false);
}

export function LyricsTextDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsTextDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lang': json['lang'] == null ? undefined : json['lang'],
        'text': json['text'] == null ? undefined : json['text'],
        'ruby': json['ruby'] == null ? undefined : ((json['ruby'] as Array<any>).map(RubyDtoFromJSON)),
    };
}

export function LyricsTextDtoToJSON(value?: LyricsTextDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lang': value['lang'],
        'text': value['text'],
        'ruby': value['ruby'] == null ? undefined : ((value['ruby'] as Array<any>).map(RubyDtoToJSON)),
    };
}

