/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LyricsVariantDto } from './LyricsVariantDto';
import {
    LyricsVariantDtoFromJSON,
    LyricsVariantDtoFromJSONTyped,
    LyricsVariantDtoToJSON,
} from './LyricsVariantDto';

/**
 * 
 * @export
 * @interface LyricsReadDto
 */
export interface LyricsReadDto {
    /**
     * 
     * @type {string}
     * @memberof LyricsReadDto
     */
    id?: string;
    /**
     * 
     * @type {Array<LyricsVariantDto>}
     * @memberof LyricsReadDto
     */
    variants?: Array<LyricsVariantDto>;
    /**
     * 
     * @type {string}
     * @memberof LyricsReadDto
     */
    referenceUrl?: string;
}

/**
 * Check if a given object implements the LyricsReadDto interface.
 */
export function instanceOfLyricsReadDto(value: object): boolean {
    return true;
}

export function LyricsReadDtoFromJSON(json: any): LyricsReadDto {
    return LyricsReadDtoFromJSONTyped(json, false);
}

export function LyricsReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'variants': json['variants'] == null ? undefined : ((json['variants'] as Array<any>).map(LyricsVariantDtoFromJSON)),
        'referenceUrl': json['referenceUrl'] == null ? undefined : json['referenceUrl'],
    };
}

export function LyricsReadDtoToJSON(value?: LyricsReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'variants': value['variants'] == null ? undefined : ((value['variants'] as Array<any>).map(LyricsVariantDtoToJSON)),
        'referenceUrl': value['referenceUrl'],
    };
}

