/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LyricsLineDto } from './LyricsLineDto';
import {
    LyricsLineDtoFromJSON,
    LyricsLineDtoFromJSONTyped,
    LyricsLineDtoToJSON,
} from './LyricsLineDto';

/**
 * 
 * @export
 * @interface LyricsVariantDto
 */
export interface LyricsVariantDto {
    /**
     * 
     * @type {string}
     * @memberof LyricsVariantDto
     */
    variant?: string;
    /**
     * 
     * @type {Array<LyricsLineDto>}
     * @memberof LyricsVariantDto
     */
    lines?: Array<LyricsLineDto>;
}

/**
 * Check if a given object implements the LyricsVariantDto interface.
 */
export function instanceOfLyricsVariantDto(value: object): boolean {
    return true;
}

export function LyricsVariantDtoFromJSON(json: any): LyricsVariantDto {
    return LyricsVariantDtoFromJSONTyped(json, false);
}

export function LyricsVariantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsVariantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'variant': json['variant'] == null ? undefined : json['variant'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(LyricsLineDtoFromJSON)),
    };
}

export function LyricsVariantDtoToJSON(value?: LyricsVariantDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'variant': value['variant'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(LyricsLineDtoToJSON)),
    };
}

