/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LyricsLine } from './LyricsLine';
import {
    LyricsLineFromJSON,
    LyricsLineFromJSONTyped,
    LyricsLineToJSON,
} from './LyricsLine';

/**
 * 
 * @export
 * @interface LyricsVariant
 */
export interface LyricsVariant {
    /**
     * 
     * @type {string}
     * @memberof LyricsVariant
     */
    variant?: string;
    /**
     * 
     * @type {Array<LyricsLine>}
     * @memberof LyricsVariant
     */
    lines: Array<LyricsLine> | null;
}

/**
 * Check if a given object implements the LyricsVariant interface.
 */
export function instanceOfLyricsVariant(value: object): boolean {
    if (!('lines' in value)) return false;
    return true;
}

export function LyricsVariantFromJSON(json: any): LyricsVariant {
    return LyricsVariantFromJSONTyped(json, false);
}

export function LyricsVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'variant': json['variant'] == null ? undefined : json['variant'],
        'lines': (json['lines'] == null ? null : (json['lines'] as Array<any>).map(LyricsLineFromJSON)),
    };
}

export function LyricsVariantToJSON(value?: LyricsVariant | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'variant': value['variant'],
        'lines': (value['lines'] == null ? null : (value['lines'] as Array<any>).map(LyricsLineToJSON)),
    };
}

