/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ruby } from './Ruby';
import {
    RubyFromJSON,
    RubyFromJSONTyped,
    RubyToJSON,
} from './Ruby';

/**
 * 
 * @export
 * @interface LyricsText
 */
export interface LyricsText {
    /**
     * 
     * @type {string}
     * @memberof LyricsText
     */
    lang: string | null;
    /**
     * 
     * @type {string}
     * @memberof LyricsText
     */
    text: string | null;
    /**
     * 
     * @type {Array<Ruby>}
     * @memberof LyricsText
     */
    ruby?: Array<Ruby>;
}

/**
 * Check if a given object implements the LyricsText interface.
 */
export function instanceOfLyricsText(value: object): boolean {
    if (!('lang' in value)) return false;
    if (!('text' in value)) return false;
    return true;
}

export function LyricsTextFromJSON(json: any): LyricsText {
    return LyricsTextFromJSONTyped(json, false);
}

export function LyricsTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsText {
    if (json == null) {
        return json;
    }
    return {
        
        'lang': json['lang'],
        'text': json['text'],
        'ruby': json['ruby'] == null ? undefined : ((json['ruby'] as Array<any>).map(RubyFromJSON)),
    };
}

export function LyricsTextToJSON(value?: LyricsText | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lang': value['lang'],
        'text': value['text'],
        'ruby': value['ruby'] == null ? undefined : ((value['ruby'] as Array<any>).map(RubyToJSON)),
    };
}

