/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LyricsText } from './LyricsText';
import {
    LyricsTextFromJSON,
    LyricsTextFromJSONTyped,
    LyricsTextToJSON,
} from './LyricsText';

/**
 * 
 * @export
 * @interface LyricsLine
 */
export interface LyricsLine {
    /**
     * 
     * @type {number}
     * @memberof LyricsLine
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof LyricsLine
     */
    time?: string;
    /**
     * 
     * @type {Array<LyricsText>}
     * @memberof LyricsLine
     */
    blocks: Array<LyricsText> | null;
}

/**
 * Check if a given object implements the LyricsLine interface.
 */
export function instanceOfLyricsLine(value: object): boolean {
    if (!('index' in value)) return false;
    if (!('blocks' in value)) return false;
    return true;
}

export function LyricsLineFromJSON(json: any): LyricsLine {
    return LyricsLineFromJSONTyped(json, false);
}

export function LyricsLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsLine {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'time': json['time'] == null ? undefined : json['time'],
        'blocks': (json['blocks'] == null ? null : (json['blocks'] as Array<any>).map(LyricsTextFromJSON)),
    };
}

export function LyricsLineToJSON(value?: LyricsLine | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'time': value['time'],
        'blocks': (value['blocks'] == null ? null : (value['blocks'] as Array<any>).map(LyricsTextToJSON)),
    };
}

