/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LyricsTextDto } from './LyricsTextDto';
import {
    LyricsTextDtoFromJSON,
    LyricsTextDtoFromJSONTyped,
    LyricsTextDtoToJSON,
} from './LyricsTextDto';

/**
 * 
 * @export
 * @interface LyricsLineDto
 */
export interface LyricsLineDto {
    /**
     * 
     * @type {number}
     * @memberof LyricsLineDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof LyricsLineDto
     */
    time?: string;
    /**
     * 
     * @type {Array<LyricsTextDto>}
     * @memberof LyricsLineDto
     */
    blocks?: Array<LyricsTextDto>;
}

/**
 * Check if a given object implements the LyricsLineDto interface.
 */
export function instanceOfLyricsLineDto(value: object): boolean {
    return true;
}

export function LyricsLineDtoFromJSON(json: any): LyricsLineDto {
    return LyricsLineDtoFromJSONTyped(json, false);
}

export function LyricsLineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LyricsLineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'time': json['time'] == null ? undefined : json['time'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(LyricsTextDtoFromJSON)),
    };
}

export function LyricsLineDtoToJSON(value?: LyricsLineDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'time': value['time'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(LyricsTextDtoToJSON)),
    };
}

