/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RubyDto
 */
export interface RubyDto {
    /**
     * 
     * @type {number}
     * @memberof RubyDto
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof RubyDto
     */
    length?: number;
    /**
     * 
     * @type {string}
     * @memberof RubyDto
     */
    text?: string;
}

/**
 * Check if a given object implements the RubyDto interface.
 */
export function instanceOfRubyDto(value: object): boolean {
    return true;
}

export function RubyDtoFromJSON(json: any): RubyDto {
    return RubyDtoFromJSONTyped(json, false);
}

export function RubyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RubyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'length': json['length'] == null ? undefined : json['length'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function RubyDtoToJSON(value?: RubyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'length': value['length'],
        'text': value['text'],
    };
}

