/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ruby
 */
export interface Ruby {
    /**
     * 
     * @type {number}
     * @memberof Ruby
     */
    index: number;
    /**
     * 
     * @type {number}
     * @memberof Ruby
     */
    length: number;
    /**
     * 
     * @type {string}
     * @memberof Ruby
     */
    text: string | null;
}

/**
 * Check if a given object implements the Ruby interface.
 */
export function instanceOfRuby(value: object): boolean {
    if (!('index' in value)) return false;
    if (!('length' in value)) return false;
    if (!('text' in value)) return false;
    return true;
}

export function RubyFromJSON(json: any): Ruby {
    return RubyFromJSONTyped(json, false);
}

export function RubyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ruby {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'length': json['length'],
        'text': json['text'],
    };
}

export function RubyToJSON(value?: Ruby | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'length': value['length'],
        'text': value['text'],
    };
}

