/* tslint:disable */
/* eslint-disable */
/**
 * TlmcPlayerBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlbumReadDto } from './AlbumReadDto';
import {
    AlbumReadDtoFromJSON,
    AlbumReadDtoFromJSONTyped,
    AlbumReadDtoToJSON,
} from './AlbumReadDto';
import type { AssetReadDto } from './AssetReadDto';
import {
    AssetReadDtoFromJSON,
    AssetReadDtoFromJSONTyped,
    AssetReadDtoToJSON,
} from './AssetReadDto';
import type { LocalizedField } from './LocalizedField';
import {
    LocalizedFieldFromJSON,
    LocalizedFieldFromJSONTyped,
    LocalizedFieldToJSON,
} from './LocalizedField';
import type { OriginalTrackReadDto } from './OriginalTrackReadDto';
import {
    OriginalTrackReadDtoFromJSON,
    OriginalTrackReadDtoFromJSONTyped,
    OriginalTrackReadDtoToJSON,
} from './OriginalTrackReadDto';

/**
 * 
 * @export
 * @interface TrackReadDto
 */
export interface TrackReadDto {
    /**
     * 
     * @type {string}
     * @memberof TrackReadDto
     */
    id?: string;
    /**
     * 
     * @type {LocalizedField}
     * @memberof TrackReadDto
     */
    name?: LocalizedField;
    /**
     * 
     * @type {number}
     * @memberof TrackReadDto
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackReadDto
     */
    disc?: number;
    /**
     * 
     * @type {string}
     * @memberof TrackReadDto
     */
    duration?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackReadDto
     */
    genre?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackReadDto
     */
    staff?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackReadDto
     */
    arrangement?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackReadDto
     */
    vocalist?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackReadDto
     */
    lyricist?: Array<string>;
    /**
     * 
     * @type {Array<OriginalTrackReadDto>}
     * @memberof TrackReadDto
     */
    original?: Array<OriginalTrackReadDto>;
    /**
     * 
     * @type {boolean}
     * @memberof TrackReadDto
     */
    originalNonTouhou?: boolean;
    /**
     * 
     * @type {AlbumReadDto}
     * @memberof TrackReadDto
     */
    album?: AlbumReadDto;
    /**
     * 
     * @type {AssetReadDto}
     * @memberof TrackReadDto
     */
    trackFile?: AssetReadDto;
    /**
     * 
     * @type {boolean}
     * @memberof TrackReadDto
     */
    hasLyrics?: boolean;
}

/**
 * Check if a given object implements the TrackReadDto interface.
 */
export function instanceOfTrackReadDto(value: object): boolean {
    return true;
}

export function TrackReadDtoFromJSON(json: any): TrackReadDto {
    return TrackReadDtoFromJSONTyped(json, false);
}

export function TrackReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackReadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : LocalizedFieldFromJSON(json['name']),
        'index': json['index'] == null ? undefined : json['index'],
        'disc': json['disc'] == null ? undefined : json['disc'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'staff': json['staff'] == null ? undefined : json['staff'],
        'arrangement': json['arrangement'] == null ? undefined : json['arrangement'],
        'vocalist': json['vocalist'] == null ? undefined : json['vocalist'],
        'lyricist': json['lyricist'] == null ? undefined : json['lyricist'],
        'original': json['original'] == null ? undefined : ((json['original'] as Array<any>).map(OriginalTrackReadDtoFromJSON)),
        'originalNonTouhou': json['originalNonTouhou'] == null ? undefined : json['originalNonTouhou'],
        'album': json['album'] == null ? undefined : AlbumReadDtoFromJSON(json['album']),
        'trackFile': json['trackFile'] == null ? undefined : AssetReadDtoFromJSON(json['trackFile']),
        'hasLyrics': json['hasLyrics'] == null ? undefined : json['hasLyrics'],
    };
}

export function TrackReadDtoToJSON(value?: TrackReadDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': LocalizedFieldToJSON(value['name']),
        'index': value['index'],
        'disc': value['disc'],
        'duration': value['duration'],
        'genre': value['genre'],
        'staff': value['staff'],
        'arrangement': value['arrangement'],
        'vocalist': value['vocalist'],
        'lyricist': value['lyricist'],
        'original': value['original'] == null ? undefined : ((value['original'] as Array<any>).map(OriginalTrackReadDtoToJSON)),
        'originalNonTouhou': value['originalNonTouhou'],
        'album': AlbumReadDtoToJSON(value['album']),
        'trackFile': AssetReadDtoToJSON(value['trackFile']),
        'hasLyrics': value['hasLyrics'],
    };
}

