/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AlbumOrderOptions = {
    Id: 'Id',
    Date: 'Date',
    Title: 'Title'
} as const;
export type AlbumOrderOptions = typeof AlbumOrderOptions[keyof typeof AlbumOrderOptions];


export function AlbumOrderOptionsFromJSON(json: any): AlbumOrderOptions {
    return AlbumOrderOptionsFromJSONTyped(json, false);
}

export function AlbumOrderOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumOrderOptions {
    return json as AlbumOrderOptions;
}

export function AlbumOrderOptionsToJSON(value?: AlbumOrderOptions | null): any {
    return value as any;
}

