/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlbumReadDto } from './AlbumReadDto';
import {
    AlbumReadDtoFromJSON,
    AlbumReadDtoFromJSONTyped,
    AlbumReadDtoToJSON,
} from './AlbumReadDto';

/**
 * 
 * @export
 * @interface AlbumReadDtoActionResult
 */
export interface AlbumReadDtoActionResult {
    /**
     * 
     * @type {object}
     * @memberof AlbumReadDtoActionResult
     */
    result?: object;
    /**
     * 
     * @type {AlbumReadDto}
     * @memberof AlbumReadDtoActionResult
     */
    value?: AlbumReadDto;
}

/**
 * Check if a given object implements the AlbumReadDtoActionResult interface.
 */
export function instanceOfAlbumReadDtoActionResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AlbumReadDtoActionResultFromJSON(json: any): AlbumReadDtoActionResult {
    return AlbumReadDtoActionResultFromJSONTyped(json, false);
}

export function AlbumReadDtoActionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumReadDtoActionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : json['result'],
        'value': !exists(json, 'value') ? undefined : AlbumReadDtoFromJSON(json['value']),
    };
}

export function AlbumReadDtoActionResultToJSON(value?: AlbumReadDtoActionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'value': AlbumReadDtoToJSON(value.value),
    };
}

