/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HlsPlaylistType = {
    Master: 'Master',
    Media: 'Media'
} as const;
export type HlsPlaylistType = typeof HlsPlaylistType[keyof typeof HlsPlaylistType];


export function HlsPlaylistTypeFromJSON(json: any): HlsPlaylistType {
    return HlsPlaylistTypeFromJSONTyped(json, false);
}

export function HlsPlaylistTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HlsPlaylistType {
    return json as HlsPlaylistType;
}

export function HlsPlaylistTypeToJSON(value?: HlsPlaylistType | null): any {
    return value as any;
}

