/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HlsSegmentWriteDto
 */
export interface HlsSegmentWriteDto {
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof HlsSegmentWriteDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    hlsSegmentPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HlsSegmentWriteDto
     */
    hlsPlaylistId?: string;
}

/**
 * Check if a given object implements the HlsSegmentWriteDto interface.
 */
export function instanceOfHlsSegmentWriteDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HlsSegmentWriteDtoFromJSON(json: any): HlsSegmentWriteDto {
    return HlsSegmentWriteDtoFromJSONTyped(json, false);
}

export function HlsSegmentWriteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HlsSegmentWriteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'hlsSegmentPath': !exists(json, 'hlsSegmentPath') ? undefined : json['hlsSegmentPath'],
        'hlsPlaylistId': !exists(json, 'hlsPlaylistId') ? undefined : json['hlsPlaylistId'],
    };
}

export function HlsSegmentWriteDtoToJSON(value?: HlsSegmentWriteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'index': value.index,
        'name': value.name,
        'hlsSegmentPath': value.hlsSegmentPath,
        'hlsPlaylistId': value.hlsPlaylistId,
    };
}

