/* tslint:disable */
/* eslint-disable */
/**
 * AuthenticationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtKeyResponse
 */
export interface JwtKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof JwtKeyResponse
     */
    publicKey?: string | null;
}

/**
 * Check if a given object implements the JwtKeyResponse interface.
 */
export function instanceOfJwtKeyResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JwtKeyResponseFromJSON(json: any): JwtKeyResponse {
    return JwtKeyResponseFromJSONTyped(json, false);
}

export function JwtKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtKeyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKey': !exists(json, 'publicKey') ? undefined : json['publicKey'],
    };
}

export function JwtKeyResponseToJSON(value?: JwtKeyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKey': value.publicKey,
    };
}

