/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OkResult
 */
export interface OkResult {
    /**
     * 
     * @type {number}
     * @memberof OkResult
     */
    statusCode?: number;
}

/**
 * Check if a given object implements the OkResult interface.
 */
export function instanceOfOkResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OkResultFromJSON(json: any): OkResult {
    return OkResultFromJSONTyped(json, false);
}

export function OkResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
    };
}

export function OkResultToJSON(value?: OkResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
    };
}

