/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaylistItemReadDto
 */
export interface PlaylistItemReadDto {
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemReadDto
     */
    trackId?: string;
    /**
     * 
     * @type {number}
     * @memberof PlaylistItemReadDto
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaylistItemReadDto
     */
    timesPlayed?: number;
    /**
     * 
     * @type {Date}
     * @memberof PlaylistItemReadDto
     */
    dateAdded?: Date;
}

/**
 * Check if a given object implements the PlaylistItemReadDto interface.
 */
export function instanceOfPlaylistItemReadDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlaylistItemReadDtoFromJSON(json: any): PlaylistItemReadDto {
    return PlaylistItemReadDtoFromJSONTyped(json, false);
}

export function PlaylistItemReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistItemReadDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trackId': !exists(json, 'trackId') ? undefined : json['trackId'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'timesPlayed': !exists(json, 'timesPlayed') ? undefined : json['timesPlayed'],
        'dateAdded': !exists(json, 'dateAdded') ? undefined : (new Date(json['dateAdded'])),
    };
}

export function PlaylistItemReadDtoToJSON(value?: PlaylistItemReadDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trackId': value.trackId,
        'index': value.index,
        'timesPlayed': value.timesPlayed,
        'dateAdded': value.dateAdded === undefined ? undefined : (value.dateAdded.toISOString()),
    };
}

