/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaylistItemAddRequest
 */
export interface PlaylistItemAddRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemAddRequest
     */
    playlistId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistItemAddRequest
     */
    playlistItemId?: string;
}

/**
 * Check if a given object implements the PlaylistItemAddRequest interface.
 */
export function instanceOfPlaylistItemAddRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlaylistItemAddRequestFromJSON(json: any): PlaylistItemAddRequest {
    return PlaylistItemAddRequestFromJSONTyped(json, false);
}

export function PlaylistItemAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistItemAddRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'playlistId': !exists(json, 'playlistId') ? undefined : json['playlistId'],
        'playlistItemId': !exists(json, 'playlistItemId') ? undefined : json['playlistItemId'],
    };
}

export function PlaylistItemAddRequestToJSON(value?: PlaylistItemAddRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'playlistId': value.playlistId,
        'playlistItemId': value.playlistItemId,
    };
}

