/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlaylistVisibility = {
    Public: 'Public',
    Private: 'Private',
    Unlisted: 'Unlisted'
} as const;
export type PlaylistVisibility = typeof PlaylistVisibility[keyof typeof PlaylistVisibility];


export function PlaylistVisibilityFromJSON(json: any): PlaylistVisibility {
    return PlaylistVisibilityFromJSONTyped(json, false);
}

export function PlaylistVisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistVisibility {
    return json as PlaylistVisibility;
}

export function PlaylistVisibilityToJSON(value?: PlaylistVisibility | null): any {
    return value as any;
}

