/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlaylistVisibility } from './PlaylistVisibility';
import {
    PlaylistVisibilityFromJSON,
    PlaylistVisibilityFromJSONTyped,
    PlaylistVisibilityToJSON,
} from './PlaylistVisibility';

/**
 * 
 * @export
 * @interface PlaylistCreateRequest
 */
export interface PlaylistCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaylistCreateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {PlaylistVisibility}
     * @memberof PlaylistCreateRequest
     */
    visibility?: PlaylistVisibility;
}

/**
 * Check if a given object implements the PlaylistCreateRequest interface.
 */
export function instanceOfPlaylistCreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlaylistCreateRequestFromJSON(json: any): PlaylistCreateRequest {
    return PlaylistCreateRequestFromJSONTyped(json, false);
}

export function PlaylistCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'visibility': !exists(json, 'visibility') ? undefined : PlaylistVisibilityFromJSON(json['visibility']),
    };
}

export function PlaylistCreateRequestToJSON(value?: PlaylistCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'visibility': PlaylistVisibilityToJSON(value.visibility),
    };
}

