/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TrackReadDto } from './TrackReadDto';
import {
    TrackReadDtoFromJSON,
    TrackReadDtoFromJSONTyped,
    TrackReadDtoToJSON,
} from './TrackReadDto';

/**
 * 
 * @export
 * @interface TrackReadDtoActionResult
 */
export interface TrackReadDtoActionResult {
    /**
     * 
     * @type {object}
     * @memberof TrackReadDtoActionResult
     */
    result?: object;
    /**
     * 
     * @type {TrackReadDto}
     * @memberof TrackReadDtoActionResult
     */
    value?: TrackReadDto;
}

/**
 * Check if a given object implements the TrackReadDtoActionResult interface.
 */
export function instanceOfTrackReadDtoActionResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackReadDtoActionResultFromJSON(json: any): TrackReadDtoActionResult {
    return TrackReadDtoActionResultFromJSONTyped(json, false);
}

export function TrackReadDtoActionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackReadDtoActionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : json['result'],
        'value': !exists(json, 'value') ? undefined : TrackReadDtoFromJSON(json['value']),
    };
}

export function TrackReadDtoActionResultToJSON(value?: TrackReadDtoActionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'value': TrackReadDtoToJSON(value.value),
    };
}

