/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackUpdateDto
 */
export interface TrackUpdateDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackUpdateDto
     */
    genre?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackUpdateDto
     */
    staff?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackUpdateDto
     */
    arrangement?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackUpdateDto
     */
    vocalist?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackUpdateDto
     */
    lyricist?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackUpdateDto
     */
    original?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackUpdateDto
     */
    originalNonTouhou?: boolean | null;
}

/**
 * Check if a given object implements the TrackUpdateDto interface.
 */
export function instanceOfTrackUpdateDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrackUpdateDtoFromJSON(json: any): TrackUpdateDto {
    return TrackUpdateDtoFromJSONTyped(json, false);
}

export function TrackUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'genre': !exists(json, 'genre') ? undefined : json['genre'],
        'staff': !exists(json, 'staff') ? undefined : json['staff'],
        'arrangement': !exists(json, 'arrangement') ? undefined : json['arrangement'],
        'vocalist': !exists(json, 'vocalist') ? undefined : json['vocalist'],
        'lyricist': !exists(json, 'lyricist') ? undefined : json['lyricist'],
        'original': !exists(json, 'original') ? undefined : json['original'],
        'originalNonTouhou': !exists(json, 'originalNonTouhou') ? undefined : json['originalNonTouhou'],
    };
}

export function TrackUpdateDtoToJSON(value?: TrackUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'genre': value.genre,
        'staff': value.staff,
        'arrangement': value.arrangement,
        'vocalist': value.vocalist,
        'lyricist': value.lyricist,
        'original': value.original,
        'originalNonTouhou': value.originalNonTouhou,
    };
}

