/* tslint:disable */
/* eslint-disable */
/**
 * MusicDataService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCredentialsDto
 */
export interface UserCredentialsDto {
    /**
     * 
     * @type {string}
     * @memberof UserCredentialsDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialsDto
     */
    password: string;
}

/**
 * Check if a given object implements the UserCredentialsDto interface.
 */
export function instanceOfUserCredentialsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UserCredentialsDtoFromJSON(json: any): UserCredentialsDto {
    return UserCredentialsDtoFromJSONTyped(json, false);
}

export function UserCredentialsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCredentialsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'password': json['password'],
    };
}

export function UserCredentialsDtoToJSON(value?: UserCredentialsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'password': value.password,
    };
}

