/* tslint:disable */
/* eslint-disable */
/**
 * AuthenticationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponse1
 */
export interface ApiResponse1 {
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponse1
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiResponse1
     */
    message?: string | null;
    /**
     * 
     * @type {object}
     * @memberof ApiResponse1
     */
    result?: object;
}

/**
 * Check if a given object implements the ApiResponse1 interface.
 */
export function instanceOfApiResponse1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiResponse1FromJSON(json: any): ApiResponse1 {
    return ApiResponse1FromJSONTyped(json, false);
}

export function ApiResponse1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponse1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ApiResponse1ToJSON(value?: ApiResponse1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'result': value.result,
    };
}

