/* tslint:disable */
/* eslint-disable */
/**
 * AuthenticationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JwtKeyResponse } from './JwtKeyResponse';
import {
    JwtKeyResponseFromJSON,
    JwtKeyResponseFromJSONTyped,
    JwtKeyResponseToJSON,
} from './JwtKeyResponse';

/**
 * 
 * @export
 * @interface JwtKeyResponseApiResponse
 */
export interface JwtKeyResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof JwtKeyResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JwtKeyResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {JwtKeyResponse}
     * @memberof JwtKeyResponseApiResponse
     */
    result?: JwtKeyResponse;
}

/**
 * Check if a given object implements the JwtKeyResponseApiResponse interface.
 */
export function instanceOfJwtKeyResponseApiResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JwtKeyResponseApiResponseFromJSON(json: any): JwtKeyResponseApiResponse {
    return JwtKeyResponseApiResponseFromJSONTyped(json, false);
}

export function JwtKeyResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtKeyResponseApiResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'result': !exists(json, 'result') ? undefined : JwtKeyResponseFromJSON(json['result']),
    };
}

export function JwtKeyResponseApiResponseToJSON(value?: JwtKeyResponseApiResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'result': JwtKeyResponseToJSON(value.result),
    };
}

