/* tslint:disable */
/* eslint-disable */
/**
 * AuthenticationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JwtRenewResult } from './JwtRenewResult';
import {
    JwtRenewResultFromJSON,
    JwtRenewResultFromJSONTyped,
    JwtRenewResultToJSON,
} from './JwtRenewResult';

/**
 * 
 * @export
 * @interface JwtRenewResultApiResponse
 */
export interface JwtRenewResultApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof JwtRenewResultApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JwtRenewResultApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {JwtRenewResult}
     * @memberof JwtRenewResultApiResponse
     */
    result?: JwtRenewResult;
}

/**
 * Check if a given object implements the JwtRenewResultApiResponse interface.
 */
export function instanceOfJwtRenewResultApiResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JwtRenewResultApiResponseFromJSON(json: any): JwtRenewResultApiResponse {
    return JwtRenewResultApiResponseFromJSONTyped(json, false);
}

export function JwtRenewResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtRenewResultApiResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'result': !exists(json, 'result') ? undefined : JwtRenewResultFromJSON(json['result']),
    };
}

export function JwtRenewResultApiResponseToJSON(value?: JwtRenewResultApiResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'result': JwtRenewResultToJSON(value.result),
    };
}

